module.exports = {
    design1 : {
        nome: 'Design Iniciante', 
        professor: 'Jonathan Franzen Fagundes', 
        descricao: 'Curso de Design iniciante', 
        conquista: 'Design', 
        titulo: 'Designer', 
        tier: '1', 
        image: 'design.png'
    },
    design2 : {
        nome: 'Design Intermediario', 
        professor: 'Jonathan Franzen Fagundes', 
        descricao: 'Curso de Design Intermediario', 
        conquista: 'Design', 
        titulo: 'Designer', 
        tier: '2', 
        image: 'design.png'
    },
    design3 : {
        nome: 'Design Avançado', 
        professor: 'Jonathan Franzen Fagundes', 
        descricao: 'Curso de Design Intermediario', 
        conquista: 'Design', 
        titulo: 'Designer', 
        tier: '2', 
        image: 'design.png'
    },


    design1Aula1 : { 
        nome: '1', 
        titulo: 'Teoria das Cores', 
        conteudo: `A teoria se tem como base o estudo dos padrões e formas que influenciam as pessoas a terem sentimentos subjetivos ou não a partir da influência delas no cérebro humano, esses padrões tem sido estudados a muitos anos por diversos estudiosos, bem como, Leonardo da Vinci, Isaac Newton, Goethe, entre outros...<br/><br/> Se tornou uma área muito extensa de estudo, e se delimitou em diversos temas específicos, como a Harmonia das cores... <br/><br/> Nela temos, a Harmonia Monocromática, a Harmonia análoga, a Harmonia complementar e a Harmonia Triádica. <br/><br/> Na harmonia monocromática, se observa o uso de apenas um padrão de cores para atingir determinada influência, onde nesse padrão é usado diferentes tonalidades, tornando essa cor mais escura ou mais clara a depender da quantidade de sombra ou luz colocada na mesma. <br/><br/> A harmonia análoga é usasda partindo de uma cor inicial, dela, são escolhidas as duas cores mais próximas do círculo cromático, para servirem de cores secundárias no projeto. <br/><br/>Enquanto na complementar, se usa da cor oposta do círculo cromático como cor secundária para tornar a cor primária em evidencia, colocando ela no uso de botões e objetos que se deseja obter destaque e colocando obviamente a cor secundaria de maneira que a torne a não se tornar o centro das atenções.<br/><br/>E então por final temos a harmonia triádica, nela se obtém a cor primaria como centro de destaque então se usam cores quase opostas que reflitam a cor inicial a partir do círculo cromático como poder ser observado no esquema a seguir, como nas outras, ele é usado para evidenciar a cor primária do projeto em questão.<br/><br/>Exercicio<br/><br/>No Site Canva inicie um projeto com logotipo, entao utilize das quatro Harmonias, uma em cada projeto para quatro logotipos diferentes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14
    },
    design1Aula2 : { 
        nome: '2', 
        titulo: 'Significado das Cores pt1', 
        conteudo: `A teoria se tem como base o estudo dos padrões e formas que influenciam as pessoas a terem sentimentos subjetivos ou não a partir da influência delas no cérebro humano, esses padrões tem sido estudados a muitos anos por diversos estudiosos, bem como, Leonardo da Vinci, Isaac Newton, Goethe, entre outros...<br/><br/> Se tornou uma área muito extensa de estudo, e se delimitou em diversos temas específicos, como a Harmonia das cores... <br/><br/> Nela temos, a Harmonia Monocromática, a Harmonia análoga, a Harmonia complementar e a Harmonia Triádica. <br/><br/> Na harmonia monocromática, se observa o uso de apenas um padrão de cores para atingir determinada influência, onde nesse padrão é usado diferentes tonalidades, tornando essa cor mais escura ou mais clara a depender da quantidade de sombra ou luz colocada na mesma. <br/><br/> A harmonia análoga é usasda partindo de uma cor inicial, dela, são escolhidas as duas cores mais próximas do círculo cromático, para servirem de cores secundárias no projeto. <br/><br/>Enquanto na complementar, se usa da cor oposta do círculo cromático como cor secundária para tornar a cor primária em evidencia, colocando ela no uso de botões e objetos que se deseja obter destaque e colocando obviamente a cor secundaria de maneira que a torne a não se tornar o centro das atenções.<br/><br/>E então por final temos a harmonia triádica, nela se obtém a cor primaria como centro de destaque então se usam cores quase opostas que reflitam a cor inicial a partir do círculo cromático como poder ser observado no esquema a seguir, como nas outras, ele é usado para evidenciar a cor primária do projeto em questão.<br/><br/>Exercicio<br/><br/>No Site Canva inicie um projeto com logotipo, entao utilize das quatro Harmonias, uma em cada projeto para quatro logotipos diferentes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14
    },
    design1Aula3 : { 
        nome: '3', 
        titulo: 'Significado das Cores pt2', 
        conteudo: `Azul<br/><br/>  Está cor está relacionado com a nobreza, tendo seu uso feito para transmitir harmonia, tranquilidade e serenidade, por se tratar de uma cor fria normalmente tem associação a depressão ou monotonia. Se tem relatos da cor azul na diminuição da pressão arterial e circulação sanguínea, tendo o céu e o mar como foco, ela é normalmente presente em culturas do povo ocidental.<br/> <br/> Verde<br/> <br/>Uma cor que tem forte associação a natureza e a vida por se ter referencia a cor das plantas, também traz consigo sentimentos de esperança, saúde, dinheiro, vitalidade e juventude, muitas vezes usada para transmitirtranquilidade. Faz parte das cores frias trazendo também maior seriedade.<br/> <br/>Amarelo<br/> <br/>Trazendo a sensação de luz e calor, está cor traz a sensação de estimular a criatividade e o raciocínio, também é usada para representar a alegria o otimismo, jovialidade e a riqueza pela cor do ouro. Contudo, se for utilizado em grandes proporções pode causar ansiedade e desespero.<br/> <br/>RoxoA cor roxa traz uma associação de espiritualidade, um certo mistério e misticismo, ela é obtida através da mistura do azul com o vermelho, e traz uma certa melancolia se utilizada em excesso. Por se tratar de uma cor fria é  usada com seriedade, relaciona a transmutação de energia, usada tanto em cultos religiosos católicos como em centros de meditação.<br/> <br/> RosaA cor do romantismo e delicadeza, sem sombra de dúvida se tem relaçãocom a feminilidade, mas contudo, não é expressamente usado por elas, os significados podem varias pela tonalidade usada, entretanto normalmente é usada para referencias o amor a inocência e a fantasia, sendo uma cor quente, em tonalidades mais escuras como o “pink” simboliza a sensualidade e o erotismo.<br/> <br/> VermelhoNesta cor se obtém a transmissão de muita energia, simbolizando o amor e a paixão, ela é uma cor quente que também se relaciona ao sangue, o poder e a violência, é conhecida por estimular a circulação sanguínea e melhorar a autoestima. Contudo para os cristãos tem relação direta com o pecado e a tentação, já no espírito revoluciona ela simboliza a luta pela justiça bem como espirito jovem revolucionário.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14 
    },
    design1Aula4 : { 
        nome: '4', 
        titulo: 'Significado das Cores pt3', 
        conteudo: `Laranja<br/><br/>Uma mistura do vermelho com o amarelo, o laranja é uma cor quente que mescla as simbologias dessas duas cores, onde transmite alegria, vitalidade e entusiasmo, também significando sucesso e prosperidade, ela tem relação com o aumento de apetite. Se utilizada de mais, está cor pode causar ansiedade e desgosto. MarromTendo por muitos relação com a terra pelo seu padrão objetivo, a cor marrom expressa, segurança, maturidade, conforto e simplicidade, também tem uso em produtos naturais e simboliza a vida saudável. Ela é uma cor que varia de quente ao neutro dependendo da tonalidade, mas quem a usa com roupas normalmente se traz a imagem de preservação da natureza, ligação com ancestrais e valorização dos recursos naturais. Apartir das informaçoes obtidas em relaçao a aula dois e tres, deseolvolva no site Canva um logotipo para cada cor trazendo consigo o significado da mesma, ela deve ser criada com base em algum serviço profissional ou produto. `, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14
    },
    design1Aula5 : { 
        nome: '5', 
        titulo: 'UX', 
        conteudo: `UX<br/>Vem com o significado de User Experience, e se trata de como o cliente pode interagir com o produto ou serviço a partir dos elementos disponibilizados, bem como o próprio nome já revela, se trata da forma que se passa informações. UX não se restringe apenas a forma com que o usuário final tem do produto, mas também é sobre oferecer um produto relevante, a forma como o disponibiliza também é importante para ser divulgado de maneira correta, imagina aqui que você tem números de quantas pessoas deveriam estar estudando UX, tentando convencer o leitor de como ele é uma dessas pessoas, pois num futuro próximo essa será (e, já é) a profissão do futuro.<br/><br/>1º Partindo desse princípio, vamos trabalhar com alguns dados, e sem nada visual, sem cores e sem estética, vamos tornar ele visível para o usuário final ter uma experiencia relevante em relação a números e dados<br/><br/>.A partir do tema, Energia e sustentabilidade, vamos elaborar um documento sobre um produto que vai diminuir os gastos de algum recurso ou melhorar a produtividade sustentável no planeta, você deve analisar o documento e buscar informações relevantes do que poder ser extraído para gerar o devido impacto ao leitor final relacionado a seu produto, e mostrar, com números, o tamanho do beneficio a qual usar seu produto estará sujeito. `, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14 
    },
    design1Aula6 : { 
        nome: '6', 
        titulo: 'UI', 
        conteudo: `UI<br/>significa User Interface, ou Interface de Usuário, dela vemos diferentes fatores como a forma que o usuário vai interagir com o suposto fato apontando, tanto como a reação que ele esperaria de um padrão de cores que pode aparentar subjetivo por determinar o sentimento mas também deve acompanhar o fluxo das informações contidas, exemplo, se você fala sobre sustentabilidade e morte por falta de recursos você, obviamente não deveria tratar de uma forma leviana, e deveria impor cores que realcem seu significado trazendo assim uma força mais em cores que expressem o sentimento associado...<br/><br/>Também relacionada a essa Interface, temos princípios de formas, tamanhos, tipos e cores, que todas vão englobar e sintetizar alguma informação que traga algum sentimento ao usuário final. <br/>Ele é visto como uma forma de descomplicar a forma que o usuário interage com situações, imagine a seguinte situação, você entra em um site, e esse site não teve um designer que entendia de UI, você procura interminavelmente por um botão para poder ir para a compra, porem sem sucesso, e é nesse momento em que pensa, seria mais fácil que esse botão tivesse uma cor que trouxesse maior visibilidade, e estivesse de alguma forma estampado para quem quisesse clicar, algo como “COMPRE AQUI” em uma cor primária seguindo o espectro de cor predefinida pelo site, a cor mais importante.<br/><br/>2º Seguindo essa ideia, vamos terminar de esculpir nosso projeto sobre Energia e sustentabilidade, partindo do princípio de formas, objetos, cores e trazendo a sensação de que a pessoa precisa ligar para adquirir o seu produto!<br/><br/>GOLDEMBERG, José. Energia e sustentabilidade. Revista de Cultura e Extensão USP, v. 14, p. 33-43, 2015, https://www.revistas.usp.br/rce/article/view/108256/106563`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14 
    },
    design1Aula7 : { 
        nome: '7', 
        titulo: 'Principios Básicos do Design', 
        conteudo: `Design Significa Projetar <br/> Para um bom Designer nao é necessário apenas beleza estética, mas também deve se ter funcionalidade e ergonomia (relações e otimização  entre homem e máquina). <br/> <br/>A relaçao de espaços em branco reforçam o equilibrio de unidades de grupos, aumentando o contraste do objetivo em questao. <br/> <br/>Dentre os principios básicos do design a proximidade é um dos mais relevantes, já que elementos do mesmo grupo devem estar proximos... Como itens de menu, banners e selos de Rodapé. <br/> <br/> Alinhamento<br/> - Os objetos devem estar sempre alinhados com algum outro elemento <br/> - Projeto fica organizado e nao visualmente poluído <br/> <br/> Texto justificado fica melhor quando ele se encontra em colunas estreitas, caso contrário, opte pelo alinhado à esquerda.<br/> <br/> Faça o possível para nao usar barras de rolagem horizontal <br/> <br/> Evite usar mais de um alinhamento de texto em seu projeto. Crie um padrao e se mantenha fiel a ele. <br/> <br/> Repetiçao <br/> Alguns aspectos devem se repetir, sao eles... <br/>-Fonte <br/> -Cores <br/> -Estilo <br/> <br/> A repetiçao ajuda a unificar elementos separados do design (da diagramaçao). <br/> <br/> Contraste <br/> Criar um atrativo visual. <br/> Elementos que nao sao exatamente os mesmos, tem-se a liberdade de fazer o contraste <br/> Contraste fraco é um resultado de confusão <br/> <br/> <br/>  Exercicios  <br/> <br/> No site figma, projete uma estrutura de banner de tres cores, onde será utilizado alguma logo criada em aula, neste banner voce irá anunciar o produto ou serviço para qual a logo foi desenvolvida. <br/> Deve ser usado harmonia complementar e análoga. <br/><br/> Neste banner deve estár presente um conjunto de tres elementos, um cabeçalho de um terço da página, um corpo de dois terços, que deve ser organizado de acordo com a estrutura de alinhamento visto nesta aula. <br/><br/> Deve ser escolhida uma fonte padrao para fazer o projeto, quanto ao alinhamento fica a seu crítério. <br/> Ponto importante destacar que deve ser escolhido cores que reflitam e realcem a logotipo e tragam confiança ao leitor, mostrando detalhes como, a importancia do produto ou serviço, o diferencial, e os beneficios a sociedade.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14 
    },
    design1Aula8 : { 
        nome: '8', 
        titulo: 'Design Thinking pt1', 
        conteudo: `O  Design Thinking  é uma metodologia ativa, colaborativa e inovadora que coloca as pessoas no centro das soluçoes. Uma forma de pensar e solucionar problemas através da empatia, da colaboraçao, da propotipaçao de ideias e da experimentaçao.<br/> <br/> Caracteristicas <br/><br/>É centrado no ser humano: Design Thinking começa com uma profunda empatia e um entendimento das necessidades e motivaçoes das pessoas.<br/><br/>É otimista: Design Thinking é a crença  funtamental de que nós todos podemos criar mudanças - nao importa quao grande é um problema, quao pouco tempo temos disponivel ou quao restrito seja o orçamento. Nao importa que restriçoes existam à sua sua volta, pensar como designer pode ser um processo divertido.<br/><br/>É experimental: Design Thinking dá a liberdade de errar e aprender com seus erros porque voce tem novas idéias, recebe feedback de outras pessoas e depois repensa suas idéia.<br/><br/>É colaborativo: Muitas mentes brilhantes sao sempre mais fortes que uma só ao resolver umd esafio. Design Thinking apresenta vantagens por considerar as múltiplas perspectivas e a criatividade dos demais para reforças a sua própria criatividade.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14 
    },
    design1Aula9 : { 
        nome: '9', 
        titulo: 'Design Thinking pt2', 
        conteudo: `Beneficios do Design Thinking<br/><br/>Desenvolve a Empatia<br/><br/>Por ter que se colocar  no lugar do usuário, a capacidade de empatia é reforçada. O objetivo final é atender as suas necessidades e alorizar a capacidade de oferecer soluçoes inovadoras.<br/><br/>Aumenta a Criatividade<br/><br/>O desenvolvimento de técnicas com grande conteúdo visual permite trabalhar com a parte mais criativa da mente ao mesmo tempo em que desenvolve habilidades análiticas.<br/><br/><br/><br/>Reforça o Trabalho em Equipe<br/><br/>Incentiva a criaçao de sinergias entre diferentes pessoas, respeitando as caracteristicas de cada um.<br/><br/>Promove Melhorias<br/><br/>Todas as idéias precisam ser validadas antes que sejam consideradas como corretas, isso permite a rápida identificaçao e resoluçao dos problemas.<br/><br/>Cria um Bom Ambiente<br/><br/>A colaboraçao permite criar um ambiente favorável à criatividade e a soluçao de problemas com foco no ser humano.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14
    },
    design1Aula10 : { 
        nome: '10', 
        titulo: 'Design Thinking pt3', 
        conteudo: `Etapas do Design Thinking<br/><br/>O Design Thinking é uma metodologia desenvolvida em etapas e que deve ser abordado como um processo único que começa com a escolha e exploraçao de um problema de forma empática e somente é finalizado quando a equipe valida e entrega a solçao, a qual deve atender os tres critérios da metodologia: <br/><br/>Desejavel humanamente<br/>Viável financeiramente<br/>Praticável tecnicamente<br/><br/>Dentre as etapas do Design Thinking podemos caracterizar.<br/><br/>Empatia: Entender quais sao os desejos e as necessidades das pessoas envolvidas no problema.<br/><br/>Definiçao do Problema: Interpretar as informaçoes e definir o problema.<br/><br/>Ideaçao:  Problema definido, é o momento de gerar idéias criativas.<br/><br/>Prototipaçao: Hora de tirar as idéias do papel e torná-ças concretas e visuais.<br/><br/>Teste:  Etapa de testas e aperfeiçoar a soluçao.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 14 
    },

    design2Aula1 : { 
        nome: '1', 
        titulo: 'Principios do Design', 
        conteudo: `Princípios do Design<br/>Oque é o design?<br/><br/>Design é a aplicação de princípios estéticos e técnicos para criar produtos visuais eficazes e atraentes. Alguns dos princípios básicos de design incluem:<br/><br/>Hierarquia: isso se refere à ordem de importância dos elementos em um projeto. Os elementos mais importantes devem ser destacados e colocados em posições privilegiadas, enquanto os menos importantes devem ser minimizados ou escondidos.<br/>Alinhamento: isso se refere à maneira como os elementos são posicionados em relação uns aos outros. Eles podem ser alinhados à esquerda, à direita, ao centro ou justificados. O alinhamento ajuda a criar ordem e clareza no projeto.<br/>Contraste: isso se refere à diferença entre os elementos em um projeto. O contraste pode ser criado usando cores, tamanhos, tipos de letra e outros elementos visuais. Ele ajuda a destacar as diferenças entre os elementos e a chamar a atenção do espectador.<br/>Equilíbrio: isso se refere à distribuição de peso visual em um projeto. Os elementos podem ser distribuídos de maneira simétrica ou assimétrica. O equilíbrio ajuda a criar uma sensação de harmonia e ordem no projeto.<br/>Esses princípios básicos de design são frequentemente usados em conjunto para criar projetos eficazes e atraentes. A aplicação correta desses princípios pode ajudar a criar projetos que sejam fáceis de entender e atraentes para o espectador.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15 
    },
    design2Aula2 : { 
        nome: '2', 
        titulo: 'Hierarquia', 
        conteudo: `Hierarquia<br/>A hierarquia é um princípio fundamental do design que se refere à ordem de importância dos elementos em um projeto. Ela ajuda a organizar informações e direcionar a atenção do espectador para os elementos mais importantes.<br/><br/>Existem várias maneiras de criar hierarquia em um projeto, como:<br/><br/>Tamanho: os elementos maiores tendem a ser vistos como mais importantes do que os menores.<br/>  Cor: as cores mais vivas e saturadas tendem a chamar mais atenção do que as cores mais fracas e desaturadas.<br/>Tipo de letra: os tipos de letra maiores e mais legíveis tendem a ser vistos como mais importantes do que os menores e menos legíveis.<br/>Posição: os elementos posicionados em áreas privilegiadas da página, como o topo ou o centro, tendem a ser vistos como mais importantes do que os elementos posicionados nas bordas.<br/>Contraste: os elementos que se destacam mais em relação ao seu fundo tendem a ser vistos como mais importantes.<br/><br/>A hierarquia é importante porque ajuda a direcionar a atenção do espectador para as informações mais importantes e a organizar as informações de maneira clara e fácil de entender. Além disso, ajuda a guiar o espectador através de um projeto, desde a informação principal até os detalhes menos importantes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15 
    },
    design2Aula3 : { 
        nome: '3', 
        titulo: 'Alinhamento', 
        conteudo: `Alinhamento<br/>O alinhamento é um princípio fundamental do design que se refere à maneira como os elementos visuais são posicionados em relação uns aos outros. Ele ajuda a criar uma sensação de ordem e coesão em um projeto.<br/><br/>Existem vários tipos de alinhamentos, como:<br/>Alinhamento à esquerda: Os elementos são alinhados à esquerda do espaço designado. Esse tipo de alinhamento é frequentemente usado em projetos de texto, como livros e artigos.<br/>Alinhamento ao centro: Os elementos são centralizados no espaço designado. Esse tipo de alinhamento é frequentemente usado em projetos de títulos e cabeçalhos.<br/>Alinhamento à direita: Os elementos são alinhados à direita do espaço designado. Esse tipo de alinhamento é frequentemente usado em projetos de texto, como livros e artigos.<br/>Alinhamento justificado: Os elementos são alinhados à esquerda e à direita do espaço designado. Esse tipo de alinhamento é frequentemente usado em projetos de texto, como livros e artigos.<br/>Alinhamento misto: Os elementos são alinhados de maneira não uniforme, criando uma sensação de movimento e dinamismo. Esse tipo de alinhamento é frequentemente associado a projetos mais criativos e contemporâneos.<br/><br/>É importante notar que o alinhamento é um princípio fundamental no design, que ajuda a criar uma sensação de ordem e coesão no projeto. Ele pode ser usado de forma estratégica para direcionar a atenção do espectador para os elementos mais importantes e para guiar o espectador através do projeto.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15 
    },
    design2Aula4 : { 
        nome: '4', 
        titulo: 'Contraste', 
        conteudo: `Contraste<br/>O contraste é um princípio fundamental do design que se refere à diferença entre os elementos visuais. Ele é usado para destacar certos elementos e criar hierarquia visual. Existem vários tipos de contraste, como:<br/>Contraste de cor: É a diferença entre as cores usadas em um projeto. Por exemplo, o contraste entre o preto e branco é o mais forte possível, enquanto o contraste entre dois tons de cinza é muito menor.<br/>Contraste de tamanho: É a diferença entre o tamanho dos elementos visuais. Por exemplo, uma imagem grande e uma pequena, ou um título grande e um subtítulo pequeno.<br/>Contraste de forma: É a diferença entre as formas dos elementos visuais. Por exemplo, uma imagem redonda e uma retangular.<br/>Contraste de estilo: É a diferença entre os estilos dos elementos visuais. Por exemplo, um elemento em estilo moderno e outro em estilo clássico.<br/>Contraste de textura: É a diferença na textura dos elementos visuais. Por exemplo, um elemento liso e outro rugoso.<br/>O contraste é importante porque ajuda a chamar a atenção para os elementos mais importantes e a criar hierarquia visual no projeto. Ele também pode ser usado para criar interesse e movimento no projeto. No entanto, é importante evitar o uso excessivo de contraste, pois isso pode tornar o projeto confuso e desordenado.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15 
    },
    design2Aula5 : { 
        nome: '5', 
        titulo: 'Equilíbrio', 
        conteudo: `Equilíbrio<br/>O equilíbrio é um princípio fundamental do design que se refere à distribuição de peso visual em um projeto. Ele ajuda a criar uma sensação de harmonia e ordem, e pode ser alcançado de duas maneiras: simétrico ou assimétrico.<br/>Equilíbrio simétrico: Ocorre quando os elementos visuais são distribuídos de maneira simétrica, criando uma sensação de ordem e estabilidade. Esse tipo de equilíbrio é frequentemente associado a projetos formais e tradicionais.<br/><br/>Equilíbrio assimétrico: Ocorre quando os elementos visuais são distribuídos de maneira assimétrica, criando uma sensação de movimento e dinamismo. Esse tipo de equilíbrio é frequentemente associado a projetos mais criativos e contemporâneos.<br/><br/>Além disso, o equilíbrio pode ser alcançado através do uso de cores, tamanhos e formas diferentes. Por exemplo, um elemento grande e escuro pode ser equilibrado por vários elementos menores e mais leves.<br/><br/>É importante notar que o equilíbrio é relativo e pode variar dependendo do projeto e do público-alvo. Por exemplo, um projeto de arte contemporânea pode utilizar uma distribuição de peso visual intencionalmente desequilibrada para criar uma sensação de tensão e movimento.<br/><br/>Em resumo, o equilíbrio é um princípio fundamental no design, que ajuda a criar uma sensação de harmonia e ordem no projeto, e pode ser alcançado de duas maneiras, simétrico ou assimétrico. Ele pode ser alcançado através do uso de cores, tamanhos e formas diferentes, e pode variar dependendo do projeto e do público-alvo.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15 
    },
    design2Aula6 : { 
        nome: '6', 
        titulo: 'Ferramentas', 
        conteudo: `Ferramentas<br/>Existem várias ferramentas de design disponíveis, mas algumas das mais populares e amplamente utilizadas incluem:<br/>Adobe Photoshop: É um software de edição de imagem raster, ou seja, trabalha com pixels. É usado para criar, editar e manipular imagens. Ele permite ajustar a cor, a exposição, a saturação, aplicar filtros, adicionar camadas, etc. Ele é usado principalmente para edição de fotografias, criação de ilustrações e tratamento de imagens.<br/>Adobe Illustrator: É um software de edição de vetores, ou seja, trabalha com traços e formas matemáticas. Ele é usado para criar gráficos vetoriais, como logotipos, ícones, ilustrações e infográficos. Ele permite criar formas complexas, aplicar estilos, sombrear, etc.<br/>Adobe InDesign: É um software de edição de layout, é usado para criar documentos impressos, como revistas, livros, catálogos e panfletos. Ele permite criar layouts complexos, trabalhar com texto e imagens, criar tabelas e gráficos, importar arquivos de outros softwares e exportar para PDF.<br/>Sketch: É um software de edição de vetores e layout, similar ao Illustrator e InDesign, mas é especialmente popular entre os designers de interface (UI) e de experiência do usuário (UX). Ele é usado para criar protótipos e telas para aplicativos e sites.<br/>Figma: É uma ferramenta de design colaborativo, que permite trabalhar com equipes remotas, dar feedbacks e compartilhar arquivos. É usado para criar protótipos e telas para aplicativos e sites.<br/>Essas são apenas algumas das ferramentas de design mais populares. Existem muitas outras opções disponíveis, como CorelDRAW, Affinity Designer, GIMP, entre outros. A escolha da ferramenta ideal dependerá do tipo de projeto que você está trabalhando e de suas necessidades específicas.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15
    },
    design2Aula7 : { 
        nome: '7', 
        titulo: 'Imagens e Vetores', 
        conteudo: `Imagens e Vetores<br/>Existem vários tipos de mídia utilizados na criação de designs, incluindo gráficos vetoriais, imagens vetoriais e imagens bitmap.<br/><br/>Gráficos vetoriais: São desenhos criados usando traços e formas matemáticas. Eles são compostos por pontos, linhas e curvas, e podem ser escalados sem perda de qualidade, ou seja, sem ficar pixelado. Exemplos de formatos de arquivos de gráficos vetoriais incluem SVG, AI, EPS.<br/><br/>Imagens vetoriais: São imagens compostas por traços e formas matemáticas, assim como os gráficos vetoriais, mas elas possuem preenchimento e textura. São utilizadas para criar ilustrações, desenhos, ícones e logotipos. Exemplos de formatos de arquivos de imagens vetoriais incluem SVG, AI, EPS.<br/><br/>Imagens bitmap: São imagens compostas por pixels, ou seja, pequenos quadrados de cor. Elas não podem ser escaladas sem perda de qualidade, ou seja, ficam pixeladas. Exemplos de formatos de arquivos de imagens bitmap incluem JPEG, PNG, GIF, BMP.<br/><br/>É importante notar que as imagens bitmap podem ser convertidas para gráficos vetoriais usando software específico, mas o processo é complexo e não garante resultados perfeitos.<br/><br/>Os gráficos vetoriais e as imagens vetoriais são mais flexíveis e escaláveis, por isso são mais comumente usados em projetos de design, enquanto as imagens bitmap são mais comumente usadas em projetos de edição de fotos e vídeos.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15 
    },
    design2Aula8 : { 
        nome: '8', 
        titulo: 'Cores e Tipografia', 
        conteudo: `Cores e Tipografia<br/>Os princípios básicos de cores e tipografia são fundamentais para a criação de designs eficazes.<br/><br/>Cores: As cores são um elemento visual importante e podem transmitir emoções e significados. Existem várias teorias de cores, como a teoria das cores primárias, secundárias e terciárias, que explicam como as cores se relacionam entre si. Além disso, existem significados psicológicos associados às cores, como o vermelho que pode ser associado a emoções fortes, como raiva e paixão. É importante usar cores de forma consciente e pensar em como elas se relacionam com o conteúdo e o objetivo do projeto.<br/><br/>Tipografia: A tipografia é outro elemento visual importante. Ela se refere à escolha e à disposição das letras e dos caracteres em um projeto. A tipografia pode ser usada para transmitir personalidade, hierarquia e legibilidade. É importante escolher fontes que sejam legíveis e apropriadas para o projeto. Além disso, é importante pensar na disposição das letras e como elas se relacionam com o resto do projeto.<br/><br/>Os princípios básicos de cores e tipografia são fundamentais para a criação de designs eficazes. Ao utilizá-los de forma consciente e pensando em como eles se relacionam com o conteúdo e o objetivo do projeto, você pode criar designs que sejam eficazes e atraentes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15 
    },
    design2Aula9 : { 
        nome: '9', 
        titulo: 'Tipografia', 
        conteudo: `Tipografia<br/>A tipografia é a escolha e a disposição das letras e dos caracteres em um projeto de design. É uma parte fundamental da comunicação visual e pode transmitir personalidade, hierarquia e legibilidade.<br/><br/>Existem vários tipos de fontes ou tipos de letra, como serif, sans-serif, script e display. Cada tipo tem suas próprias características e são mais adequadas para certos projetos. Por exemplo, as fontes serif são geralmente consideradas mais tradicionais e formais, enquanto as fontes sans-serif são consideradas mais modernas e informais.<br/><br/>Além da escolha da fonte, é importante pensar na disposição das letras. Isso inclui coisas como tamanho, espaçamento, alinhamento e hierarquia. O tamanho e o espaçamento das letras podem afetar a legibilidade, enquanto o alinhamento e a hierarquia podem afetar a organização visual do projeto.<br/><br/>A tipografia também pode ser usada para transmitir emoções ou personalidade. Por exemplo, uma fonte cursiva ou com serifa pode transmitir elegância, enquanto uma fonte sem serifa pode transmitir simplicidade.<br/><br/>É importante escolher fontes que sejam legíveis e apropriadas para o projeto, e pensar na disposição das letras e como elas se relacionam com o resto do projeto. Ao usar a tipografia de forma consciente, você pode criar designs que sejam eficazes e atraentes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 15
    },
    design2Aula10 : { 
        nome: '10',
         titulo: 'Exercicios', 
         conteudo: `Exercicios<br/>Aqui estão alguns exercícios práticos para aplicar os conceitos de design aprendidos:<br/>Crie um cartão de visita: Escolha uma fonte legível e apropriada, e crie um layout simples e organizado para o cartão. Considere a hierarquia, o alinhamento e o contraste ao colocar o nome, o cargo e o contato do indivíduo.<br/>Crie um logotipo: Escolha uma fonte que transmita a personalidade da marca e crie um símbolo simples e fácil de reconhecer. Considere a hierarquia e o alinhamento ao posicionar o nome da marca com o símbolo.<br/>Crie um banner para redes sociais: Escolha imagens e fontes que sejam atraentes e apropriadas para o projeto. Considere a hierarquia e o contraste ao posicionar o texto e as imagens no banner.<br/>Crie um design para camiseta: Escolha uma imagem ou fonte que seja apropriada e atraente. Considere o equilíbrio e o contraste ao posicionar o design na camiseta.<br/>Crie uma landing page: Escolha uma fonte legível e apropriada, e crie um layout simples e organizado para a landing page. Considere a hierarquia, o alinhamento e o contraste ao colocar o título, o texto e as imagens.<br/>Esses são apenas alguns exemplos de exercícios práticos, mas lembre-se que a prática é a chave para melhorar habilidades de design. Experimente com diferentes fontes, imagens e layouts para desenvolver seu próprio estilo e se sentir confortável com as ferramentas de design.`, 
         video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
         cursoId: 15
    },
    
    design3Aula1 : { 
        nome: '1', 
        titulo: 'Design de interação', 
        conteudo: `Design de interação é o processo de projetar interfaces digitais que permitem aos usuários interagir e se comunicar com aplicativos, dispositivos e sistemas. Ele enfoca a criação de interfaces eficientes, intuitivas e satisfatórias que tornam a interação do usuário com a tecnologia fluida e agradável.<br/><br/>O design de interação envolve a compreensão dos usuários e suas necessidades, a definição de objetivos de interação, a criação de protótipos e a avaliação de interfaces. Também inclui a consideração de fatores como acessibilidade, usabilidade e segurança.<br/><br/>Existem várias metodologias e técnicas utilizadas no design de interação, como design centrado no usuário, design de fluxo de trabalho, design de estrutura de informação, design de interação baseado em gestos e design de interação baseado em voz.<br/><br/>Alguns dos principais princípios do design de interação incluem:<br/><br/>Simplicidade: Criar interfaces que sejam fáceis de usar e entender.<br/><br/>Consistência: Usar convenções e padrões de design consistentes para ajudar os usuários a navegar e compreender as interfaces.<br/><br/>Feedback: Fornecer feedback claro e imediato sobre as ações dos usuários.<br/><br/>Flexibilidade: Permitir que os usuários personalizem e configurem as interfaces para atender às suas necessidades específicas.<br/><br/>Acessibilidade: Criar interfaces que possam ser usadas por pessoas com diferentes habilidades e necessidades.<br/><br/>Enquanto o design de interação é muitas vezes associado a aplicativos e dispositivos móveis, ele também é aplicado a outros tipos de tecnologias, como sistemas de automação residencial, dispositivos vestíveis, veículos autônomos e realidade virtual.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula2 : { 
        nome: '2', 
        titulo: 'Atividade', 
        conteudo: `Atividade: Design de Interação para um Aplicativo de Receitas<br/><br/>Objetivo: Criar um protótipo de uma interface de usuário para um aplicativo de receitas que seja fácil de usar, intuitivo e atraente.<br/><br/>Defina o público-alvo: Identifique quem serão os usuários do aplicativo, suas necessidades e objetivos de interação. Por exemplo, o aplicativo pode ser direcionado para pessoas que gostam de cozinhar, que estão à procura de novas receitas, e que querem uma forma fácil de acessá-las.<br/><br/>Defina os objetivos de interação: Identifique as principais tarefas que os usuários realizarão no aplicativo, como buscar e salvar receitas, criar listas de compras, e avaliar as receitas.<br/><br/>Crie um fluxo de trabalho: Desenhe o fluxo de trabalho do aplicativo, ou seja, como os usuários irão navegar pelo aplicativo para realizar as suas tarefas. Isso pode incluir telas como "Início", "Busca", "Receitas salvadas" e "Lista de compras".<br/><br/>Desenhe a interface: Utilize ferramentas de desenho, como papel e lápis ou software de design, para desenhar a interface do aplicativo. Considere a disposição dos elementos na tela, as cores, as fontes e os ícones. Certifique-se de que a interface seja consistente e fácil de usar.<br/><br/>Crie um protótipo: Utilize uma ferramenta de prototipagem, como Figma ou InVision, para criar um protótipo interativo da interface. Isso permitirá que você e outras pessoas testem a interface antes de desenvolver o aplicativo de verdade.<br/><br/>Teste com usuários: Peça para pessoas que sejam semelhantes ao seu público-alvo testarem o protótipo e forneçam feedback sobre a usabilidade, a intuitividade e a atratividade da interface. Utilize esses comentários para fazer ajustes no design.<br/><br/>Implemente e avalie: Utilize as informações coletadas para implementar a interface no aplicativo de verdade e avaliar sua eficiência e sua facilidade de uso, caso necessário, faça ajustes e melhorias.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula3 : { 
        nome: '3', 
        titulo: 'Design de interface de usuário', 
        conteudo: `Design de interface de usuário (UI, do inglês User Interface Design) é o processo de projetar interfaces digitais que permitem aos usuários interagir e se comunicar com aplicativos, dispositivos e sistemas. Ele enfoca a criação de interfaces que sejam fáceis de usar, intuitivas e atraentes, tornando a interação do usuário com a tecnologia agradável e eficiente.<br/><br/>O design de UI envolve a compreensão dos usuários e suas necessidades, a definição de objetivos de interação, a criação de protótipos e a avaliação de interfaces. Ele também inclui a consideração de fatores como acessibilidade, usabilidade e segurança.<br/><br/>Existem várias metodologias e técnicas utilizadas no design de UI, como design centrado no usuário, design de fluxo de trabalho, design de estrutura de informação, design de interação baseado em gestos e design de interação baseado em voz.<br/><br/>Alguns dos principais princípios do design de UI incluem:<br/><br/>Simplicidade: Criar interfaces que sejam fáceis de usar e entender.<br/><br/>Consistência: Usar convenções e padrões de design consistentes para ajudar os usuários a navegar e compreender as interfaces.<br/><br/>Feedback: Fornecer feedback claro e imediato sobre as ações dos usuários.<br/><br/>Flexibilidade: Permitir que os usuários personalizem e configurem as interfaces para atender às suas necessidades específicas.<br/><br/>Acessibilidade: Criar interfaces que possam ser usadas por pessoas com diferentes habilidades e necessidades.<br/><br/>A parte do design de UI esta mais voltada para a estética, layout e a disposição da informação na tela, enquanto o design de interação está mais voltado para os mecanismos de interação, como botões, links e menus. O design de UI e o design de interação trabalham juntos para criar interfaces que sejam eficientes e agradáveis de usar.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula4 : { 
        nome: '4', 
        titulo: 'Atividade', 
        conteudo: `Escolha um produto ou aplicativo que você usa regularmente e analise sua interface de usuário. Anote as coisas que você gosta e as coisas que acha que poderiam ser melhoradas.<br/><br/>Crie um wireframe ou protótipo de baixa fidelidade da tela principal do aplicativo ou produto que você escolheu, usando ferramentas como o papel e lápis ou ferramentas digitais como o Balsamiq ou o Figma.<br/><br/>Peça a um amigo ou colega para testar o seu wireframe, pedindo-lhes para realizar tarefas específicas e observando como eles interagem com o design. Anote as dificuldades ou problemas que eles encontraram.<br/><br/>Faça alterações no seu wireframe baseado no feedback e teste novamente com outra pessoa.<br/><br/>Crie uma versão final do protótipo e escreva uma breve descrição das decisões de design e justificativas por trás delas.<br/><br/>Apresente o seu protótipo e documentação para um grupo de colegas ou mentores e solicite feedback e sugestões para melhorias futuras.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula5 : { 
        nome: '5', 
        titulo: 'Design de sistemas', 
        conteudo: `Design de sistemas é o processo de projetar e planejar sistemas completos e complexos, como sistemas de negócios, sistemas de informação e sistemas de engenharia. Isso envolve a integração de vários componentes, como hardware, software, processos e pessoas, para alcançar objetivos específicos. Aqui estão alguns passos gerais para design de sistemas:<br/><br/>Entenda o problema ou necessidade: Antes de começar a projetar um sistema, é importante compreender o problema ou necessidade que ele deve resolver. Isso pode incluir entrevistar stakeholders, realizar pesquisas e coletar dados.<br/><br/>Defina os objetivos do sistema: Depois de entender o problema, defina os objetivos específicos do sistema. Eles devem ser mensuráveis, alcançáveis e relevantes para o problema.<br/><br/>Faça um levantamento de requisitos: Identifique e documente todos os requisitos do sistema, incluindo funcionalidades, restrições, regras de negócios e requisitos não funcionais, como desempenho, segurança e escalabilidade.<br/><br/>Projete a arquitetura do sistema: Crie a estrutura geral do sistema, incluindo componentes, interfaces e fluxo de dados. Isso pode incluir desenhar diagramas de blocos, fluxo de dados e diagramas de componentes.<br/><br/>Implemente e teste o sistema: Use a arquitetura e os requisitos para desenvolver e implementar o sistema. Teste o sistema para garantir que ele atenda aos objetivos e requisitos.<br/><br/>Mantenha e melhore o sistema: Depois de implementado, o sistema deve ser monitorado e mantido para garantir que continue atendendo aos objetivos e requisitos. Isso pode incluir fazer melhorias e atualizações ao longo do tempo.<br/><br/>Esses são os passos básicos para o design de sistemas, mas é importante lembrar que o processo pode ser complexo e exigir muitos detalhes e iteratividade. Além disso, é importante envolver todos os stakeholders no processo para garantir que as decisões de design reflitam as necessidades e objetivos da organização.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula6 : { 
        nome: '6', 
        titulo: 'Atividade', 
        conteudo: `Escolha um sistema que você gostaria de projetar, como um sistema de gerenciamento de estoque para uma loja, ou um sistema de gerenciamento de equipes para uma empresa.<br/><br/>Entreviste os stakeholders do sistema, como gerentes, funcionários e usuários finais, para entender suas necessidades e desafios atuais com o sistema atual (se houver) ou com o processo.<br/><br/>Defina os objetivos do sistema baseado nas necessidades identificadas nas entrevistas. Certifique-se de que os objetivos sejam mensuráveis, alcançáveis e relevantes.<br/><br/>Faça um levantamento de requisitos, identificando e documentando todos os requisitos funcionais e não funcionais do sistema. Isso pode incluir a lista de funcionalidades desejadas, restrições, regras de negócios e requisitos de desempenho, segurança e escalabilidade.<br/><br/>Projete a arquitetura do sistema, criando diagramas de blocos, fluxo de dados e diagramas de componentes para ilustrar a estrutura geral do sistema e como os componentes se relacionam.<br/><br/>Implemente uma versão protótipo do sistema, usando a arquitetura e os requisitos como base. Teste o protótipo para garantir que ele atenda aos objetivos e requisitos.<br/><br/>Refine o design do sistema com base nos resultados dos testes e receba feedback dos stakeholders.<br/><br/>Finalize o desenvolvimento e implementação do sistema e implemente plano de manutenção e melhoria contínua.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16
    },
    design3Aula7 : { 
        nome: '7', 
        titulo: 'Design de serviços', 
        conteudo: `Design de serviços é o processo de criar, desenvolver e otimizar serviços para atender às necessidades dos clientes de maneira eficiente e eficaz. Alguns dos principais passos envolvidos no design de serviços incluem:<br/><br/>Identificação de necessidades: Identifique as necessidades dos clientes e entenda como um serviço pode atender a essas necessidades.<br/><br/>Projeto de serviço: Crie um projeto para o serviço que inclua a descrição do serviço, fluxo de trabalho, processos e recursos necessários.<br/><br/>Teste e validação: Teste o projeto do serviço com clientes-alvo para verificar se ele atende às suas necessidades e se é viável.<br/><br/>Implementação: Implemente o serviço e treine a equipe responsável por prestar o serviço.<br/><br/>Monitoramento e avaliação: Monitorar o desempenho do serviço e coletar feedback dos clientes para identificar pontos de melhoria.<br/><br/>Melhoria continua: Continuar a melhorar e otimizar o serviço com base nos resultados do monitoramento e avaliação.<br/><br/>Além disso, é importante considerar a experiência do cliente (CX) ao longo de todo o ciclo de vida do serviço e garantir que a comunicação e a colaboração sejam eficazes entre todas as partes interessadas (como equipes internas, parceiros e provedores de serviços).`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula8 : { 
        nome: '8', 
        titulo: 'Atividade', 
        conteudo: `Atividade: Design de um serviço de entrega de comida<br/><br/>Identificação de necessidades: Faça uma pesquisa com potenciais clientes para entender suas necessidades e desejos em relação a um serviço de entrega de comida. Pergunte sobre suas expectativas em relação ao tempo de entrega, variedade de opções de comida, facilidade de pedido, preços, etc.<br/><br/>Projeto de serviço: Com base nas informações coletadas na etapa 1, crie um projeto para o serviço de entrega de comida. Inclua uma descrição detalhada do serviço, fluxo de trabalho, processos e recursos necessários. Pense em como os pedidos serão feitos (online, telefone, etc.), como a comida será preparada e transportada, e como os pagamentos serão processados.<br/><br/>Teste e validação: Faça um teste piloto do serviço com um grupo selecionado de clientes-alvo. Peça feedback sobre as suas experiências e se o serviço atende às suas necessidades. Use as informações coletadas para ajustar e melhorar o projeto do serviço.<br/><br/>Implementação: Com o projeto ajustado, implemente o serviço de entrega de comida. Treine a equipe responsável por prestar o serviço e estabeleça processos e procedimentos para garantir que o serviço seja prestado de maneira consistente e de qualidade.<br/><br/>Monitoramento e avaliação: Monitorar o desempenho do serviço e coletar feedback dos clientes. Use essas informações para identificar pontos de melhoria e oportunidades de crescimento.<br/><br/>Melhoria continua: Continuar a melhorar e otimizar o serviço com base nos resultados do monitoramento e avaliação. Adicione novas opções de comida, experimente novos métodos de entrega, e ajustar preços e outras políticas de acordo com as necessidades do cliente e do mercado.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula9 : { 
        nome: '9', 
        titulo: 'Design de experiência do usuário', 
        conteudo: `Design de experiência do usuário (UX) é o processo de projetar sistemas, produtos e serviços para torná-los eficazes, eficientes e agradáveis de usar. O UX design é baseado em princípios de pesquisa de usuário, design centrado no usuário e teste de usuário, com o objetivo de criar soluções que sejam fáceis de usar, úteis e desejadas pelos usuários.<br/><br/>Para projetar uma boa experiência de usuário, é necessário seguir alguns passos:<br/><br/>Compreender o usuário: É importante conhecer o público-alvo do seu produto ou serviço. Faça pesquisas e entrevistas para entender suas necessidades, desejos e comportamentos.<br/><br/>Definir o problema: Com base nas necessidades do usuário, defina o problema ou desafio que o seu produto ou serviço precisa resolver.<br/><br/>Criar soluções: Projete soluções para o problema identificado. Utilize técnicas de design como brainstorming, sketching e prototyping para criar várias opções de design.<br/><br/>Testar com usuários: Realize testes com usuários para validar as soluções projetadas. Peça feedback e observe como os usuários interagem com o produto ou serviço.<br/><br/>Implementar e manter: Com base nos resultados dos testes, implemente a solução final e monitore continuamente a experiência do usuário. Faça ajustes e melhorias contínuas para garantir que o produto ou serviço continue atendendo às necessidades do usuário.<br/><br/>O UX design é importante porque ajuda a criar soluções que atendem às necessidades dos usuários e, assim, aumenta a satisfação do usuário e a probabilidade de sucesso do produto ou serviço.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16
    },
    design3Aula10 : { 
        nome: '10',
         titulo: 'Atividade', 
         conteudo: `Atividade: Melhoria de experiência de usuário em um site de e-commerce<br/><br/>Objetivo: Melhorar a experiência do usuário no site de uma loja virtual de roupas.<br/><br/>Passo 1: Compreender o usuário<br/><br/>Realize entrevistas com potenciais clientes da loja virtual para entender suas necessidades, desejos e comportamentos de compra.<br/><br/>Faça uma pesquisa de mercado para conhecer a concorrência e identificar as principais tendências no setor.<br/><br/>Passo 2: Definir o problema<br/><br/>Com base nas entrevistas e pesquisas, identifique os problemas ou desafios que os usuários enfrentam ao navegar e comprar no site. Por exemplo: falta de filtros de busca, dificuldade de encontrar informações de tamanhos e cores, ou carrinho de compras que não guarda itens.<br/><br/>Passo 3: Criar soluções<br/><br/>Projete soluções para os problemas identificados. Utilize técnicas de design como sketching, wireframing e prototyping para criar várias opções de design. Por exemplo, adicione filtros de busca avançadas, inclua imagens de modelos com diferentes tamanhos e cores, ou permita que os usuários salvem seus carrinhos de compras para continuar mais tarde.<br/><br/>Passo 4: Testar com usuários<br/><br/>Realize testes com usuários para validar as soluções projetadas. Peça feedback e observe como os usuários interagem com o site. Utilize ferramentas de análise de dados para medir o desempenho do site.<br/><br/>Passo 5: Implementar e manter<br/><br/>Com base nos resultados dos testes, implemente as melhorias e monitore continuamente a experiência do usuário. Faça ajustes e melhorias contínuas para garantir que o site continue atendendo às necessidades dos usuários.<br/><br/>Essa atividade é apenas uma amostra para ensinar como melhorar a experiência do usuário em um site de e-commerce, mas os princípios de UX podem ser aplicados em diversos outros tipos de projetos.`, 
         video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
         cursoId: 16
    },
    design3Aula11 : { 
        nome: '11', 
        titulo: 'Design de realidade virtual', 
        conteudo: `Design de realidade virtual (VR) e realidade aumentada (AR) é o processo de criar e projetar experiências imersivas e interativas para usuários. Isso inclui tanto a criação de conteúdo como a concepção da interface do usuário e a interação.<br/><br/>Aqui estão alguns passos básicos para design de VR e AR:<br/><br/>Compreender o usuário: É importante entender quem serão os usuários finais da sua experiência VR/AR e quais são suas necessidades, desejos e comportamentos. Isso pode ser feito através de entrevistas e pesquisas.<br/><br/>Definir o objetivo: Defina o objetivo da sua experiência VR/AR. Isso pode ser algo como educar, entreter ou simplesmente fornecer uma nova forma de visualizar informações.<br/><br/>Escolher a tecnologia certa: Escolha a tecnologia certa para sua experiência VR/AR. Isso pode ser VR completo com óculos e sensores, ou AR usando dispositivos como smartphones ou tablets.<br/><br/>Projetar a interface do usuário: Projete a interface do usuário para sua experiência VR/AR, incluindo como os usuários interagirão com ela. Isso pode incluir elementos como menus, botões, gestos e até mesmo comandos de voz.<br/><br/>Desenvolver o conteúdo: Desenvolva o conteúdo para sua experiência VR/AR, incluindo elementos como texturas, modelos 3D, áudio e efeitos visuais.<br/><br/>Testar e iterar: Teste a sua experiência VR/AR com usuários e obtenha feedback. Use essa informação para fazer melhorias e iterar no design.<br/><br/>Manter e atualizar: Continue a manter e atualizar a sua experiência VR/AR, garantindo que ela esteja sempre funcionando corretamente e atendendo às necessidades dos usuários.<br/><br/>Design de realidade virtual e aumentada é uma área em constante evolução e é importante estar atento às novas tecnologias e tendências. Designers de VR e AR precisam ter habilidades de design tradicionais, bem como conhecimentos técnicos para trabalhar com as tecnologias específicas.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula12 : { 
        nome: '12', 
        titulo: 'Atividade', 
        conteudo: `Atividade: Criando uma experiência VR/AR<br/><br/>Objetivo: Criar uma experiência VR/AR simples, mas imersiva e interativa, usando técnicas de design de realidade virtual e aumentada.<br/><br/>Etapas:<br/><br/>Escolha um objetivo para sua experiência VR/AR. Pode ser algo como mostrar uma visita guiada em um museu ou simular uma aula de cirurgia.<br/><br/>Escolha a tecnologia certa para sua experiência. Isso pode ser VR completo com óculos e sensores, ou AR usando smartphones ou tablets.<br/><br/>Crie uma história e roteiro para sua experiência. Isso deve incluir elementos como personagens, diálogos e interações.<br/><br/>Projete a interface do usuário para sua experiência. Isso deve incluir elementos como menus, botões, gestos e até mesmo comandos de voz.<br/><br/>Desenvolva o conteúdo para sua experiência. Isso pode incluir elementos como texturas, modelos 3D, áudio e efeitos visuais.<br/><br/>Teste sua experiência com usuários e obtenha feedback. Use essa informação para fazer melhorias e iterar no design.<br/><br/>Refinando e aperfeiçoando a experiência.<br/><br/>Compartilhe sua experiência com amigos e familiares e peça feedback para continuar aperfeiçoando.<br/><br/>Lembre-se de que essa é uma atividade básica e que existem muitos outros aspectos importantes a serem considerados ao projetar uma experiência VR/AR, como ergonomia, usabilidade, segurança e acessibilidade.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula13 : { 
        nome: '13', 
        titulo: 'Design de jogos', 
        conteudo: `Design de jogos é o processo de criar e desenvolver jogos eletrônicos. Ele inclui a criação de histórias, personagens, mecânicas de jogo, arte e música, além da programação e testes. O design de jogos é uma área multidisciplinar que envolve habilidades em design, programação, arte, animação, música e narrativa.<br/><br/>Aqui estão algumas etapas gerais para desenvolver um jogo:<br/><br/>Criação de conceito: Neste estágio, os desenvolvedores criam uma ideia para um jogo e a desenvolvem em um conceito geral. Isso inclui a criação de personagens, histórias e mecânicas de jogo.<br/><br/>Design de jogo: Neste estágio, os desenvolvedores criam documentos de design detalhando como o jogo funcionará, incluindo as mecânicas de jogo, a jogabilidade e a estrutura do jogo.<br/><br/>Desenvolvimento: Neste estágio, os desenvolvedores usam ferramentas de programação para criar o jogo. Isso inclui a criação de gráficos, música, efeitos sonoros e código.<br/><br/>Testes e validação: Neste estágio, os desenvolvedores testam o jogo e o validam com jogadores para garantir que ele esteja funcionando corretamente e seja divertido de jogar.<br/><br/>Lançamento: Após o jogo ser desenvolvido e testado, é lançado para o público.<br/><br/>Existem muitas outras etapas e detalhes que entram em jogo na criação de um jogo, mas essas são as etapas principais. Além disso, o design de jogos é uma área em constante evolução, com novas tecnologias e tendências surgindo regularmente.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula14 : { 
        nome: '14', 
        titulo: 'Atividade', 
        conteudo: `Atividade: Design de jogos<br/><br/>Escolha um gênero de jogo: Escolha um gênero de jogo para trabalhar, como aventura, jogos de ação, jogos de estratégia, jogos de corrida, etc.<br/><br/>Crie uma história: Escreva uma história curta que seja adequada para o gênero de jogo escolhido. Considere a trama, os personagens, o enredo e o objetivo final do jogo.<br/><br/>Desenhe a interface do usuário: Desenhe uma interface do usuário para o jogo usando papel e lápis. Isso inclui a tela inicial, menus, opções, etc.<br/><br/>Crie personagens e cenários: Desenhe personagens e cenários para o jogo. Isso inclui personagens jogáveis, personagens não jogáveis, inimigos, etc.<br/><br/>Desenvolva mecânicas de jogo: Escreva uma lista de mecânicas de jogo que serão incluídas no jogo. Isso inclui como o jogador se move, como o jogador interage com os objetos no jogo, como o jogador ganha pontos, etc.<br/><br/>Desenvolva o jogo: Use ferramentas de desenvolvimento de jogos para criar o jogo. Isso inclui a criação de gráficos, música, efeitos sonoros e código.<br/><br/>Teste e valide o jogo: Teste o jogo com jogadores para garantir que ele esteja funcionando corretamente e seja divertido de jogar.<br/><br/>Faça ajustes e melhorias: Faça ajustes e melhorias no jogo com base nos comentários dos jogadores.<br/><br/>Lancamento: Após o jogo ser desenvolvido e testado, é lançado para o público.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula15 : { 
        nome: '15', 
        titulo: 'Design de marca e identidade visual', 
        conteudo: `Design de marca e identidade visual é o processo de criação e desenvolvimento de uma marca e sua representação visual. Isso inclui elementos como logotipos, tipografia, cores, imagens e outros elementos gráficos. O objetivo é criar uma identidade visual coerente que represente a marca e a diferencie de outras marcas no mercado.<br/><br/>Para criar uma marca e uma identidade visual eficazes, é importante seguir alguns passos:<br/><br/>Compreender o público-alvo: é importante compreender a quem a marca se destina, para que possa criar uma identidade visual que seja atraente e relevante para eles.<br/><br/>Estudar a concorrência: é importante conhecer as outras marcas no mercado e como elas se apresentam visualmente, para que possa criar uma identidade visual que se diferencie delas.<br/><br/>Defina os valores e a personalidade da marca: é importante definir os valores e a personalidade da marca, para que a identidade visual possa refleti-los.<br/><br/>Criar um logotipo: Crie um logotipo que reflita a marca e seja fácil de reconhecer e se lembrar.<br/><br/>Escolha as cores: Escolha uma paleta de cores que seja coerente com a marca e seja atraente para o público-alvo.<br/><br/>Escolha a tipografia: Escolha uma fonte que seja legível e coerente com a marca.<br/><br/>Crie uma guia de estilo: Crie uma guia de estilo que inclua todos os elementos da identidade visual da marca, incluindo logotipo, cores, tipografia e outros elementos gráficos.<br/><br/>Aplique-o: Aplique a identidade visual em todos os materiais de marketing e comunicação, incluindo cartões de visita, folhetos, websites, etc.<br/><br/>Mantenha-o consistente: Mantenha a identidade visual consistente em todos os materiais de marketing e comunicação para construir uma marca forte e reconhecível.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16
    },
    design3Aula16 : { 
        nome: '16', 
        titulo: 'Atividade', 
        conteudo: `Atividade: Criação de uma Identidade Visual para uma Empresa<br/><br/>Objetivo: Criar uma identidade visual coerente e atraente para uma empresa fictícia chamada "EcoBike"<br/><br/>Passos:<br/><br/>Faça uma pesquisa sobre o público-alvo da EcoBike: EcoBike é uma empresa que vende bicicletas elétricas e acessórios. O público-alvo seriam pessoas preocupadas com meio ambiente, que gostam de se deslocar de bicicleta e que procuram comodidade e praticidade.<br/><br/>Estude a concorrência: Faça uma pesquisa das outras empresas no mercado de bicicletas elétricas e identifique como elas se apresentam visualmente.<br/><br/>Defina os valores e a personalidade da marca: EcoBike é uma empresa preocupada com meio ambiente, inovação, comodidade e praticidade.<br/><br/>Crie um logotipo: Crie um logotipo que reflita esses valores e seja fácil de reconhecer e se lembrar. Pode ser utilizado uma bicicleta elétrica como elemento principal do logo.<br/><br/>Escolha as cores: Escolha uma paleta de cores verde e cinza, que remetem à natureza e ecologia.<br/><br/>Escolha a tipografia: Escolha uma fonte moderna e limpa, que transmita inovação e praticidade.<br/><br/>Crie uma guia de estilo: Crie uma guia de estilo que inclua todos os elementos da identidade visual da marca, incluindo logotipo, cores, tipografia e outros elementos gráficos.<br/><br/>Aplique-o: Aplique a identidade visual em um cartão de visita, folheto e website fictícios para a EcoBike.<br/><br/>Peça feedback para amigos e colegas: Peça feedback sobre a identidade visual criada e faça ajustes se necessário.<br/><br/>Lembre-se de que o design de marca e identidade visual é um processo contínuo e é importante manter a consistência em todas as peças de comunicação e marketing.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula17 : { 
        nome: '17', 
        titulo: 'Design de tipografia', 
        conteudo: `Design de tipografia avançado é a arte de selecionar e combinar tipos de letra para criar uma hierarquia visual e transmitir uma mensagem de maneira eficaz. Aqui estão algumas dicas para aprimorar suas habilidades de design de tipografia:<br/><br/>Conheça as diferençes entre os tipos de letra: Existem muitos tipos diferentes de letra, como serif, sans-serif, script e display. Cada tipo tem suas próprias características e funciona melhor em diferentes contextos.<br/><br/>Entenda a hierarquia de tipografia: A hierarquia de tipografia é a ordem em que as informações são apresentadas, desde títulos até corpo de texto. Isso ajuda a guiar o olhar do leitor e a comunicar a importância das informações.<br/><br/>Jogue com tamanhos e pesos: Os tamanhos e pesos diferentes de tipos de letra podem ser usados ​​para criar contraste e destacar informações importantes.<br/><br/>Explore combinações de tipos de letra: Experimente combinar diferentes tipos de letra para criar contraste e interesse visual. Mas tenha cuidado para não exagerar combinações diferentes, pois isso pode criar confusão.<br/><br/>Aprenda as boas práticas de legibilidade: A legibilidade é a capacidade de um tipo de letra ser facilmente lido. Certifique-se de que os tipos de letra escolhidos são fáceis de ler em diferentes tamanhos e em diferentes suportes.<br/><br/>Estude designers de tipografia famosos: Estude o trabalho de designers famosos como Paula Scher, David Carson e Jessica Walsh para obter inspiração e ver como eles usam a tipografia de maneira criativa.<br/><br/>Pratique: Como com qualquer habilidade, a prática é essencial para melhorar suas habilidades de design de tipografia. Crie projetos pessoais ou participe de desafios de design para praticar e aprimorar suas habilidades.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16 
    },
    design3Aula18 : { 
        nome: '18', 
        titulo: 'Atividade', 
        conteudo: `Atividade: Design de tipografia avançado<br/><br/>Objetivo: Aplicar as técnicas de design de tipografia avançado para criar um projeto com uma hierarquia visual clara e eficaz.<br/><br/>Material necessário: Computador com software de design gráfico (como Illustrator ou InDesign), fonte de sua escolha.<br/><br/>Passo 1: Escolha um tema para o seu projeto. Pode ser qualquer coisa, desde um cartaz de evento até um design de capa de livro.<br/><br/>Passo 2: Escolha as fontes que você deseja usar para o projeto. Certifique-se de escolher pelo menos duas fontes diferentes, uma para os títulos e outra para o corpo de texto.<br/><br/>Passo 3: Crie um esboço do seu projeto. Defina a hierarquia visual, ou seja, quais informações serão destacadas e em que ordem elas serão apresentadas.<br/><br/>Passo 4: Abra o software de design gráfico e comece a criar o seu projeto. Certifique-se de seguir a hierarquia visual definida no passo 3 e experimente com diferentes tamanhos e pesos de letra para destacar informações importantes.<br/><br/>Passo 5: Explore diferentes combinações de tipos de letra para criar contraste e interesse visual. Certifique-se de que as combinações escolhidas sejam legíveis e fáceis de ler.<br/><br/>Passo 6: Revisar e ajustar. Verifique se o projeto está transmitindo a mensagem desejada e se a legibilidade é adequada. Faça ajustes finais como necessário.<br/><br/>Passo 7: Compartilhe o seu projeto. Envie para amigos, familiares e/ou colegas para obter feedback e continuar a aprender e aprimorar suas habilidades de design de tipografia avançada.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 16
    },
    design3Aula19 : { 
        nome: '19',
         titulo: 'Design de ilustração e animação', 
         conteudo: `Design de ilustração e animação é um campo criativo que envolve a criação de imagens e animações para fins artísticos, comerciais e educacionais.<br/><br/>Para se tornar um designer de ilustração e animação, é importante desenvolver habilidades em desenho, pintura, composição, storyboard e animação. É também importante estar familiarizado com softwares de edição de imagem e animação, como o Adobe Illustrator, Photoshop, After Effects e outros.<br/><br/>Aqui está uma atividade para ajudá-lo a começar a desenvolver suas habilidades em design de ilustração e animação:<br/><br/>Atividade: Design de ilustração e animação<br/><br/>Objetivo: Criar uma animação curta utilizando desenhos ilustrados à mão e técnicas de animação básicas.<br/><br/>Material necessário: papel, lápis, caneta, scanner, software de animação (como o Adobe Flash ou Toon Boom).<br/><br/>Passo 1: Escolha um curta história para animar. Pode ser uma história que você escreveu, ou algo que você encontrou online.<br/><br/>Passo 2: Faça um esboço rápido do seu história. Desenhe cada quadro da história em papel, usando lápis e caneta.<br/><br/>Passo 3: Escane os desenhos e importe-os para o software de animação.<br/><br/>Passo 4: Adicione movimento aos desenhos. Use as ferramentas de animação do software para criar movimentos suaves e fluídos.<br/><br/>Passo 5: Adicione efeitos sonoros e trilha sonora. Escolha música e efeitos sonoros adequados para acompanhar sua animação.<br/><br/>Passo 6: Revise e ajuste a animação. Verifique se a história está sendo contada de forma clara e se os movimentos e efeitos sonoros estão sincronizados corretamente.<br/><br/>Passo 7: Compartilhe sua animação. Envie-a para amigos, familiares e/ou colegas para obter feedback e continuar a aprender e aprimorar suas habilidades em design de ilustração e animação.`, 
         video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
         cursoId: 16
    },
    design3Aula20 : { 
        nome: '20',
         titulo: 'Atividade', 
         conteudo: `Atividade: Design de ilustração e animação<br/><br/>Objetivo: Criar uma ilustração animada com um personagem ou cena.<br/><br/>Material necessário: papel, lápis, caneta, scanner, software de animação (como o Adobe Flash, Adobe Animate, Procreate)<br/><br/>Passo 1: Escolha um personagem ou cena para ilustrar. Pode ser inspirado em algo que você gosta, ou criado do zero.<br/><br/>Passo 2: Faça um esboço rápido do seu personagem ou cena. Desenhe-o em papel, usando lápis e caneta.<br/><br/>Passo 3: Escane o desenho e importe-o para o software de animação.<br/><br/>Passo 4: Crie as diferentes poses e expressões do personagem ou cena. Utilize as ferramentas de desenho do software para criar as variações necessárias.<br/><br/>Passo 5: Adicione movimento à ilustração. Utilize as ferramentas de animação do software para criar movimentos suaves e fluídos.<br/><br/>Passo 6: Adicione efeitos visuais. Utilize as ferramentas de efeitos visuais para dar vida e profundidade à sua ilustração animada.<br/><br/>Passo 7: Revise e ajuste a ilustração animada. Verifique se tudo está funcionando corretamente, e se está satisfeito com o resultado final.<br/><br/>Passo 8: Compartilhe sua ilustração animada. Envie-a para amigos, familiares e/ou colegas para obter feedback e continuar a aprender e aprimorar suas habilidades em design de ilustração e animação.`, 
         video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
         cursoId: 16
    },
    design3Aula21 : { 
        nome: '21',
         titulo: 'Design de mídia digital', 
         conteudo: `Design de mídia digital é o processo de criar conteúdo visual e interativo para uso em dispositivos eletrônicos, como computadores, smartphones, tablets, televisões e outros. Isso inclui coisas como websites, aplicativos, jogos, banners publicitários, vídeos e muito mais.<br/><br/>Para começar a estudar design de mídia digital, algumas habilidades importantes incluem:<br/><br/>Conhecimento de softwares de design: Ferramentas como Adobe Photoshop, Illustrator e InDesign são fundamentais para a criação de conteúdo visual.<br/><br/>Conhecimento de HTML, CSS e JavaScript: Esses são os principais linguagens de programação usadas para criar websites e aplicativos.<br/><br/>Conhecimento de boas práticas de design: Isso inclui usar princípios de design como hierarquia, alinhamento e contraste para criar conteúdo visual atraente e fácil de navegar.<br/><br/>Conhecimento de estratégias de SEO: Isso inclui técnicas para ajudar seu conteúdo a ser encontrado pelos mecanismos de busca e melhorar sua classificação.<br/><br/>Conhecimento de tendências e tecnologias emergentes: É importante ficar atualizado com as últimas tendências e tecnologias para criar conteúdo que esteja sempre atualizado e relevante.<br/><br/>Atividade: Design de um Website<br/><br/>Objetivo: Criar um website simples usando HTML, CSS e JavaScript.<br/><br/>Material Necessário: Um editor de código (como o Sublime Text, Atom ou Visual Studio Code), uma conta gratuita no GitHub (opcional)<br/><br/>Passo 1: Escolha um tema para o seu website. Pode ser sobre um hobby, um projeto ou uma empresa fictícia.<br/><br/>Passo 2: Crie a estrutura básica do seu website usando HTML. Utilize as tags básicas como head, body, div e p para criar uma estrutura básica.<br/><br/>Passo 3: Adicione estilo ao seu website usando CSS. Utilize seletores, propriedades e valores para estilizar o seu website.<br/><br/>Passo 4: Adicione interatividade ao seu website usando JavaScript. Utilize eventos, funções e manipulação de DOM para criar interações com o usuário.<br/><br/>Passo 5: Teste e depure o seu website. Verifique se está funcionando corretamente e se está satisfeito com o resultado final.<br/><br/>Passo 6: Compartilhe seu website. Você pode usar o GitHub Pages para hospedar seu website`, 
         video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
         cursoId: 16
    },
    design3Aula22 : { 
        nome: '22',
         titulo: 'Design thinking', 
         conteudo: `Design thinking é uma metodologia criativa que é usada para resolver problemas e criar soluções inovadoras. Ele se concentra em entender as necessidades do usuário e criar soluções que sejam úteis, desejáveis e viáveis. As metodologias ágeis, como o Scrum e o Kanban, são usadas para gerenciar projetos e colaborar em equipe de forma eficaz e flexível. Elas também se concentram em entregar valor rapidamente e garantir que o trabalho seja adaptado às necessidades do negócio.<br/><br/>Scrum é uma metodologia ágil de gerenciamento de projetos que é comumente usada para desenvolver software. Ele se concentra em entregar valor rapidamente e garantir que o trabalho seja adaptado às necessidades do negócio. A equipe Scrum é composta por um Scrum Master, que é responsável por garantir que as regras do Scrum sejam seguidas, um Product Owner, que é responsável por definir o escopo e priorizar as tarefas, e uma equipe de desenvolvimento, que é responsável por implementar as tarefas.<br/><br/>Kanban é outra metodologia ágil de gerenciamento de projetos que é usada para visualizar e limitar o fluxo de trabalho. Ele se concentra em entregar valor rapidamente e garantir que o trabalho seja adaptado às necessidades do negócio. Kanban é muito flexível e pode ser usado em qualquer tipo de projeto ou equipe. Ele se concentra em visualizar o fluxo de trabalho e limitar o número de tarefas em andamento a qualquer momento.`, 
         video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
         cursoId: 16
    },
    design3Aula23 : { 
        nome: '23',
         titulo: 'Atividade', 
         conteudo: `Atividade:<br/><br/>Escolha um projeto ou tarefa que você gostaria de gerenciar usando Scrum ou Kanban.<br/><br/>Use a metodologia Scrum para definir o escopo, priorizar as tarefas e implementar as tarefas.<br/><br/>Use a metodologia Kanban para visualizar e limitar o fluxo de trabalho.<br/><br/>Compare as duas metodologias e determine qual delas funciona melhor para o seu projeto ou tarefa.<br/><br/>Atividade:<br/><br/>Escolha um problema ou desafio que você gostaria de resolver em sua empresa ou organização.<br/><br/>Use a metodologia de design thinking para entender as necessidades dos usuários e criar soluções possíveis. Isso pode incluir entrevistar usuários, criar protótipos e testar ideias.<br/><br/>Escolha uma metodologia ágil, como o Scrum ou o Kanban, para gerenciar o projeto e colaborar com sua equipe.<br/><br/>Use técnicas de design thinking e metodologias ágeis para desenvolver e implementar sua solução.<br/><br/>Faça uma avaliação para ver se a solução atende às necessidades do usuário e se ela é viável. Se necessário, volte para o passo 2 e repita o processo.`, 
         video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
         cursoId: 16
    },
}