module.exports = {
  photoshop1: {
    nome: "Photoshop Iniciante",
    professor: "Jonathan Franzen Fagundes",
    descricao: "Curso de Photoshop iniciante",
    conquista: "Photoshop",
    titulo: "Photoshoper",
    tier: "1",
    image: "photoshop.png",
  },
  photoshop2: {
    nome: "Photoshop Intermediario",
    professor: "Jonathan Franzen Fagundes",
    descricao: "Curso de Photoshop Intermediario",
    conquista: "Photoshop",
    titulo: "Photoshoper",
    tier: "2",
    image: "photoshop.png",
  },
  photoshop3: {
    nome: "Photoshop Avançado",
    professor: "Jonathan Franzen Fagundes",
    descricao: "Curso de Photoshop Intermediario",
    conquista: "Photoshop",
    titulo: "Photoshoper",
    tier: "2",
    image: "photoshop.png",
  },

  photoshop1Aula1: {
    nome: "1",
    titulo: "Introduçao ao Photoshop",
    conteudo: `<h5>Introduçao ao Photoshop<h5/><br/>Explorar a barra de menus na parte superior da tela e familiarizar-se com as opções disponíveis. <br/><br/> Arquivo: permite abrir, salvar, importar e exportar arquivos, além de configurar opções de impressão e outras configurações do programa.<br/><br/>Editar: contém comandos comuns de edição, como desfazer, refazer, recortar, copiar e colar.<br/><br/>Imagem: permite ajustar as configurações de imagem, como brilho, contraste e saturação, além de aplicar filtros e transformações.<br/><br/>Camada: permite criar, editar e excluir camadas, além de aplicar máscaras e ajustar a opacidade das camadas.<br/><br/>Seleção: contém ferramentas de seleção, como seleção de mágico, seleção de varinha mágica e seleção de pincel.<br/><br/>Ferramentas: contém todas as ferramentas disponíveis no Photoshop, incluindo ferramentas de desenho, de seleção, de retoque e de texto.<br/><br/>Janela: permite acessar as diferentes janelas do Photoshop, como camadas, histórico, propriedades e outras.<br/><br/>Ajuda: contém informações sobre o programa, incluindo dicas e tutoriais, além de opções para atualizar o programa e obter suporte técnico.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula2: {
    nome: "2",
    titulo: "Ferramentas",
    conteudo: `<h5>Ferramentas da barra lateral esquerda<h5/><br/>Localizar e explorar as ferramentas na barra lateral esquerda da tela.<br/><br/>Seleção retangular: permite selecionar áreas retangulares de uma imagem.<br/><br/>Seleção de mágico: permite selecionar áreas semelhantes de cor em uma imagem.<br/><br/>Pincel: permite pintar na imagem com diferentes texturas e tamanhos de pincel.<br/><br/>Borracha: permite apagar áreas da imagem.<br/><br/>Lapis: permite desenhar linhas precisas na imagem.<br/><br/>Texto: permite adicionar texto à imagem.<br/><br/>Formas: permite adicionar formas geométricas à imagem.<br/><br/>Gotas de tinta: permite adicionar efeitos de tinta à imagem.<br/><br/>Ferramenta de seleção de varinha mágica: permite selecionar áreas de imagem com base na cor.<br/><br/>Ferramenta de seleção de lasso: permite selecionar áreas da imagem usando formas livres.<br/><br/>Ferramenta de seleção de polígono: permite selecionar áreas da imagem usando formas poligonais.<br/><br/>Ferramenta de seleção de mover: permite mover áreas selecionadas de uma imagem.<br/><br/>Zoom: permite ampliar ou diminuir a visualização da imagem.<br/><br/>Pipeta: permite selecionar uma cor de uma imagem.<br/><br/>Explorar as janelas de camadas, histórico e propriedades na parte direita da tela.<br/><br/>Aprender a personalizar a sua área de trabalho, movendo e redimensionando as janelas.<br/><br/>Aprender a abrir e salvar arquivos no Photoshop.<br/><br/>Aprender a criar novos documentos e definir suas configurações.<br/><br/>Explorar as opções de zoom e navegação na tela.<br/><br/>Dicas:<br/><br/>Use as teclas de atalho para acessar as ferramentas rapidamente.<br/><br/>Personalize sua área de trabalho para que atenda às suas necessidades.<br/><br/>Salve seus trabalhos frequentemente para evitar perdas.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula3: {
    nome: "3",
    titulo: "Janelas de camadas",
    conteudo: `<h5>Janelas de camadas</h5><br/>Explorar as janelas de camadas, histórico e propriedades na parte direita da tela.<br/><br/>Janela de camadas: mostra todas as camadas presentes na imagem, incluindo suas configurações de opacidade e máscaras. Permite criar, editar e excluir camadas, além de organizá-las em grupos.<br/><br/>Janela de histórico: mostra todas as ações realizadas na imagem em ordem cronológica. Permite desfazer e refazer ações, bem como voltar para um estado específico da imagem.<br/><br/>Janela de propriedades: mostra as configurações de uma camada ou seleção selecionada. Permite ajustar as configurações de opacidade, preenchimento, estilo de camada, entre outros.<br/><br/>Aprender a personalizar a sua área de trabalho, movendo e redimensionando as janelas.<br/><br/>Movendo janelas: você pode mover uma janela clicando no título da janela e arrastando-a para a nova posição desejada.<br/><br/>Redimensionando janelas: você pode redimensionar uma janela clicando e arrastando os cantos ou as bordas da janela. Além disso, você também pode usar o comando "Janela" no menu superior e selecionar "Tamanho da janela" para digitar o tamanho desejado em pixels.<br/><br/>Ancorando janelas: você pode ancorar uma janela a outra, para que quando uma janela é movida, a outra segue junto. Para fazer isso, arraste uma janela até uma borda de outra janela, até que você veja uma seta verde, solte o mouse e as janelas ficarão ancoradas.<br/><br/>Organizar janelas: você pode organizar janelas usando o comando "Janela" no menu superior e selecionando "Organizar" para organizar as janelas em uma disposição específica.<br/><br/>Ocultando janelas: você também pode ocultar janelas usando o comando "Janela" no menu superior e selecionando a janela desejada. Isso pode ser útil quando você precisa de mais espaço na tela.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula4: {
    nome: "4",
    titulo: "Abrir e Salvar",
    conteudo: `<h5>Abrir e Salvar documentos</h5><br/>Aprender a abrir e salvar arquivos no Photoshop.<br/><br/>Abrir arquivos: você pode abrir arquivos no Photoshop usando o comando "Arquivo" no menu superior e selecionando "Abrir". Isso abrirá a caixa de diálogo "Abrir", onde você pode navegar pelo seu computador e selecionar o arquivo desejado. Também é possível abrir arquivos com o atalho de teclado "Ctrl + O"<br/><br/>Salvar arquivos: você pode salvar arquivos no Photoshop usando o comando "Arquivo" no menu superior e selecionando "Salvar" ou "Salvar como". "Salvar" salvará o arquivo atual com o nome atual, enquanto "Salvar como" abrirá uma caixa de diálogo para você escolher um novo nome e local para salvar o arquivo. Também é possível salvar arquivos com o atalho de teclado "Ctrl + S"<br/><br/>Salvar arquivos como outros formatos: você pode salvar arquivos no Photoshop em diferentes formatos, como JPEG, PNG ou GIF, usando o comando "Arquivo" no menu superior e selecionando "Salvar como" e escolhendo o formato desejado.<br/><br/>Autosave: O Photoshop tem uma opção de auto-salvar, que salva o seu arquivo automaticamente a cada alguns minutos. Esta opção é desativada por padrão, mas pode ser ativada nas configurações do programa.<br/><br/>Backup: É sempre recomendado fazer backup dos seus arquivos de trabalho, salvando-os em outro dispositivo ou nuvem. Isso garantirá que você tenha uma cópia do seu trabalho caso algo aconteça com o seu computador.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula5: {
    nome: "5",
    titulo: "Criaçao e definiçao",
    conteudo: `<h5>Criaçao e definiçao</h5><br/>Aprender a criar novos documentos e definir suas configurações.<br/><br/>Aprender a criar novos documentos e definir suas configurações no Photoshop é simples e pode ser feito de várias maneiras. Aqui estão algumas dicas para criar novos documentos:<br/><br/>Criar novo documento: você pode criar um novo documento no Photoshop usando o comando "Arquivo" no menu superior e selecionando "Novo". Isso abrirá a caixa de diálogo "Novo", onde você pode definir as configurações do novo documento, como o tamanho, a resolução e a cor de fundo. Também é possível criar um novo documento com o atalho de teclado "Ctrl + N"<br/><br/>Configurar novo documento: você pode definir as configurações do novo documento, como o tamanho, a resolução e a cor de fundo, na caixa de diálogo "Novo". O tamanho do documento pode ser definido em pixels, polegadas ou centímetros. A resolução é a quantidade de pixels por polegada no documento e afeta a qualidade da imagem. A cor de fundo pode ser definida como branca, preta ou qualquer outra cor.<br/><br/>Adicionar camadas: Quando você cria um novo documento, ele vem com uma única camada de fundo. No entanto, você pode adicionar novas camadas para organizar o seu trabalho. Isso pode ser feito usando o comando "Camada" no menu superior e selecionando "Nova camada" ou usando o atalho de teclado "Ctrl + Shift + N"<br/><br/>Perfil de Cor: É importante selecionar o perfil de cor correto antes de criar um novo documento, pois isso afeta como as cores serão exibidas na tela e na impressão. O padrão é RGB (vermelho, verde e azul) para tela e CMYK (ciano, magenta, amarelo e preto) para impressão.<br/><br/>Presets: O Photoshop tem vários presets pré-definidos para diferentes tipos de projetos, como cartões de visita, banners e capas de livros. Usando esses presets você pode criar novos documentos com as configurações corretas e evitar a necessidade de definir as configurações manualmente.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula6: {
    nome: "6",
    titulo: "Zoom e Navegação",
    conteudo: `<h5>Zoom e Navegação </h5><br/>Explorar as opções de zoom e navegação na tela.<br/><br/>Zoom: Para aumentar ou diminuir a imagem na tela, você pode usar as opções de zoom no menu "Exibir" no topo da tela ou usar os atalhos de teclado "Ctrl +" para aumentar e "Ctrl -" para diminuir. Você também pode usar a roda do mouse para aumentar ou diminuir o zoom.<br/><br/>Zoom com o cursor: Para zoom para uma área específica da imagem, você pode selecionar a ferramenta "Zoom" na barra lateral esquerda e clicar e arrastar o cursor sobre a área que deseja ampliar.<br/><br/>Zoom para tela inteira: Para ver a imagem inteira, você pode usar o comando "Exibir" no menu superior e selecionar "Tela cheia" ou usar o atalho de teclado "Ctrl + 0"<br/><br/>Pan: Para mover a imagem na tela, você pode usar a ferramenta "Pan" na barra lateral esquerda e clicar e arrastar a imagem para a posição desejada.<br/><br/>Navegação rápida: Você também pode usar as setas no teclado para mover a imagem na tela, pressionando a seta para cima, para baixo, para esquerda ou para direita.<br/><br/>Navegação com miniaturas: Para visualizar a imagem como um todo, você pode usar a janela "Navegação" na parte inferior da tela. Isso mostra uma miniatura da imagem inteira e você pode mover a caixa de seleção para ver diferentes áreas da imagem.<br/><br/>Exibir grade e guias: Para ajudar a alinhar objetos na imagem, você pode ativar a grade e as guias no Photoshop. Isso pode ser feito usando o comando "Exibir" no menu superior e selecionando "Grade" e "Guias".`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula7: {
    nome: "7",
    titulo: "Dicas",
    conteudo: `</h5>Dicas:</h5><br/>Use as teclas de atalho para acessar as ferramentas rapidamente.<br/><br/>Usar teclas de atalho é uma maneira rápida e eficiente de acessar as ferramentas no Photoshop. Aqui estão algumas dicas para ajudá-lo a usar as teclas de atalho:<br/><br/>Teclas de atalho para ferramentas: Cada ferramenta no Photoshop tem uma tecla de atalho associada a ela. Por exemplo, a tecla "B" é usada para selecionar a ferramenta "Pincel", a tecla "E" é usada para selecionar a ferramenta "Eraser" e assim por diante.<br/><br/>Teclas de atalho para modos de ferramentas: Algumas ferramentas possuem modos diferentes, como a ferramenta "Selection", que tem modos de seleção de "Rectangular" e "Eliptica". Esses modos também possuem teclas de atalho, como "M" para "Rectangular" e "Shift + M" para "Eliptica".<br/><br/>Teclas de atalho para opções de ferramentas: Algumas ferramentas possuem opções adicionais, como a ferramenta "Pincel" que possui opções de "Aumentar ou Diminuir o tamanho do pincel" e "Aumentar ou Diminuir a opacidade do pincel". Essas opções também possuem teclas de atalho, como "]" para aumentar o tamanho do pincel e "[" para diminuir.<br/><br/>Teclas de atalho para comandos gerais: O Photoshop possui teclas de atalho para comandos gerais, como "Ctrl + Z" para desfazer uma ação, "Ctrl + Shift + Z" para refazer uma ação e "Ctrl + N" para criar um novo documento.<br/><br/>Personalizar teclas de atalho: Você pode personalizar as teclas de atalho no Photoshop para atender às suas necessidades. Isso pode ser feito usando o menu "Edit" no topo da tela e selecionando "Keyboard Shortcuts".<br/><br/>Existem muitas teclas de atalho no Photoshop, e algumas delas podem variar de acordo com a versão do software e a configuração do sistema. `,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula8: {
    nome: "8",
    titulo: "Teclas de Atalho",
    conteudo: `<h5>Teclas de Atalho</h5><br/>Algumas teclas de atalho comuns incluem:<br/><br/>Ctrl + N: Cria um novo documento<br/>Ctrl + O: Abre um arquivo<br/>Ctrl + S: Salva o arquivo atual<br/>Ctrl + W: Fecha o arquivo atual<br/>Ctrl + Z: Desfaz a última ação<br/>Ctrl + Shift + Z: Refaz a última ação desfeita<br/>Ctrl + T: Ativa a ferramenta de Transformação<br/>Ctrl + Alt + Shift + T: Repete a última transformação<br/>Ctrl + D: Desfaz a seleção<br/>Ctrl + Shift + D: Recria a última seleção<br/>Ctrl + J: Cria uma cópia da camada atual<br/>Ctrl + Shift + N: Cria uma nova camada<br/>Ctrl + Alt + Shift + E: Cria uma nova camada com todas as camadas visíveis<br/>Ctrl + Alt + Shift + S: Salva uma cópia do arquivo<br/>Ctrl + Alt + Shift + W: Fecha todos os arquivos<br/>Ctrl + Alt + Shift + N: Cria uma nova pasta de camadas<br/>Ctrl + Alt + Shift + J: Cria uma cópia da pasta de camadas atual<br/>Ctrl + Shift + M: Ativa a ferramenta Marquee<br/>Ctrl + Shift + L: Ajusta o brilho e contraste<br/>Ctrl + Shift + B: Ajusta a saturação<br/>Ctrl + Shift + H: Ativa a ferramenta Histórico<br/>Ctrl + Shift + P: Ativa a ferramenta Pincel`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula9: {
    nome: "9",
    titulo: "Atividade",
    conteudo: `<h5>Atividade  <h5><br/>Abra o Photoshop e crie um novo documento com as configurações de sua escolha.<br/><br/>Usando as teclas de atalho, selecione as ferramentas de "Pincel", "Lápis", "Borracha" e "Selection" e experimente usá-las em seu documento.<br/><br/>Experimente usar as teclas de atalho para aumentar e diminuir o tamanho das ferramentas e alterar suas opções, como opacidade. Use teclas de atalho para desfazer e refazer suas ações.<br/><br/>Personalize as teclas de atalho das ferramentas que você usa com mais frequência, usando o menu "Edit" e selecionando "Keyboard Shortcuts"<br/><br/>Faça um exercício de escrever num papel todas as teclas de atalho que você usou e decorá-las<br/><br/>Faça essa atividade por alguns dias seguidos, e verá como isso irá ajudar a tornar o uso do photoshop mais rapido e eficiente.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula10: {
    nome: "10",
    titulo: "Seleçao de Ferramentes e Camadas",
    conteudo: `<h5>Seleçao de Ferramentes e Camadas</h5><br/>Selecionar ferramentas e camadas no Photoshop é essencial para trabalhar com suas imagens.<br/><br/>Para selecionar uma ferramenta, você pode clicar na ferramenta desejada na barra lateral esquerda da tela ou usar as teclas de atalho correspondentes. Também é possível selecionar ferramentas clicando e mantendo pressionado o botão esquerdo do mouse sobre a ferramenta atual, o que exibirá uma lista de ferramentas relacionadas.<br/><br/>Para selecionar uma camada, você pode clicar na camada desejada na janela Camadas na parte direita da tela. Também é possível selecionar várias camadas de uma só vez pressionando a tecla Ctrl enquanto clica nas camadas desejadas.<br/><br/>Você também pode selecionar camadas utilizando a ferramenta de seleção de camadas, que é representada por um ícone de mão com um ponto de exclamação. Com essa ferramenta, é possível selecionar camadas clicando nelas na tela de trabalho.<br/><br/>É importante notar que ao selecionar uma camada, todas as edições serão feitas apenas na camada selecionada, permitindo que você trabalhe com camadas individuais sem afetar as outras.<br/><br/>Uma atividade para se fazer é:<br/><br/>Abrir uma imagem no Photoshop<br/><br/>Adicionar algumas camadas extras, como textos e formas<br/><br/>Testar as diferentes ferramentas de seleção de camadas e ferramentas para entender como elas funcionam<br/><br/>Experimentar trabalhar com as camadas selecionadas, movendo-as, redimensionando-as, aplicando filtros, etc.<br/><br/>Salvar a imagem e comparar com a original.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },

  photoshop1Aula11: {
    nome: "11",
    titulo: "Ediçao Básica",
    conteudo: `</h5>Ediçao Básica</h5><br/>A edição básica de imagens no Photoshop inclui ajustes como brilho e contraste, recorte e redimensionamento.<br/><br/>Para ajustar o brilho e contraste de uma imagem, você pode usar as opções na barra de menus "Imagem" > "Ajustes" > "Brilho/Contraste". Você também pode usar a ferramenta de ajuste de brilho e contraste, que é representada por um ícone de sol com duas setas. Com essa ferramenta, você pode clicar e arrastar para aumentar ou diminuir o brilho e contraste da imagem.<br/><br/>Para recortar uma imagem, você pode usar a ferramenta de recorte, que é representada por um ícone de câmera. Com essa ferramenta, você pode selecionar uma área da imagem para recortar. Também é possível usar as opções na barra de menus "Imagem" > "Recortar".<br/><br/>Para redimensionar uma imagem, você pode usar as opções na barra de menus "Imagem" > "Tamanho da imagem" ou pressionar "Ctrl + Alt + I" no teclado. Isso abrirá a caixa de diálogo "Tamanho da imagem", onde você pode ajustar as configurações de tamanho da imagem, como largura, altura e resolução.<br/><br/>Uma atividade para se fazer é:<br/><br/>Abrir uma imagem no Photoshop<br/><br/>Aplicar ajustes de brilho e contraste na imagem<br/><br/>Experimentar usando a ferramenta de recorte para recortar diferentes áreas da imagem<br/><br/>Ajustar o tamanho da imagem usando as opções "Tamanho da imagem"<br/><br/>Salvar a imagem e comparar com a original.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula12: {
    nome: "12",
    titulo: "Camadas",
    conteudo: `<h5>Camadas</h5><br/>As camadas são uma das características mais importantes do Photoshop e permitem que você edite suas imagens de forma organizada e não destrutiva. Cada elemento da imagem é colocado em uma camada separada, permitindo que você ajuste, mova ou exclua elementos sem afetar outras partes da imagem.<br/><br/>Você pode ver as camadas na janela "Camadas", que geralmente é localizada na parte direita da tela. Cada camada tem seus próprios ajustes, como opacidade, modo de mesclagem e filtros, que você pode ajustar clicando na camada.<br/><br/>As máscaras de camada são uma ferramenta adicional que permite que você esconda ou mostre partes de uma camada. Elas são representadas por uma camada adicional com uma máscara de camada branca ou preta. A máscara de camada branca mostra a camada, enquanto a preta esconde a camada. Você também pode usar uma variedade de ferramentas de desenho para desenhar na máscara de camada e controlar a visibilidade da camada.<br/><br/>Uma atividade para se fazer é:<br/><br/>Abrir uma imagem no Photoshop<br/><br/>Criar nova camada e desenhar algo na camada<br/><br/>Brincar com os modos de mesclagem e opacidade da camada<br/><br/>Adicionar uma máscara de camada à imagem e desenhar na máscara para controlar a visibilidade da camada.<br/><br/>Salvar a imagem e comparar com a original.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula13: {
    nome: "13",
    titulo: "Filtros e Efeitos",
    conteudo: `<h5>Filtros e Efeitos</h5><br/>O Photoshop possui uma variedade de filtros e efeitos que você pode aplicar às suas imagens para criar diferentes efeitos visuais. Alguns exemplos de filtros populares incluem:<br/><br/>Filtro de desfoque: suaviza as bordas de uma imagem, criando um efeito de desfoque. Existem vários tipos de filtros de desfoque, como Desfoque Gaussiano, Desfoque de Movimento e Desfoque Radial.<br/><br/>Filtro de nitidez: aumenta a nitidez e os detalhes de uma imagem.<br/><br/>Filtro de distorção: distorce uma imagem de várias maneiras, como ondulação, cisalhamento e zigue-zague.<br/><br/>Filtro de textura: adiciona texturas à imagem, como madeira, pedra ou metal.<br/><br/>Alguns exemplos de efeitos populares incluem:<br/><br/>Efeito de camada: permite que você aplique efeitos de camada, como sombreamento, sombra e brilho, à sua imagem.<br/><br/>Efeito de camada de estilo: permite que você aplique estilos predefinidos, como estilos de borda, sombra e textura, à suma imagem.<br/><br/>Efeito de camada de ajuste: permite que você ajuste a cor, a saturação, o brilho e outras configurações de sua imagem.<br/><br/>Uma atividade para fazer é:<br/><br/>Abrir uma imagem no Photoshop<br/><br/>Explorar diferentes filtros e efeitos disponíveis na pasta Filtro ou Efeito<br/><br/>Escolher alguns filtros e efeitos para aplicar à imagem<br/><br/>Experimentar com diferentes configurações e opções para cada filtro ou efeito<br/><br/>Comparar a imagem original com a imagem editada e observar as diferenças.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula14: {
    nome: "14",
    titulo: "Ferramentas de texto e Vetoriais",
    conteudo: `<h5>Ferramentas de texto e Vetoriais</h5><br/>O Photoshop possui ferramentas poderosas para criar texto e formas vetoriais. Aqui estão algumas coisas que você pode aprender:<br/><br/>Criando texto: você pode criar texto usando a ferramenta de texto, que é encontrada na barra de ferramentas lateral esquerda. Depois de selecionar a ferramenta, você pode clicar e arrastar na tela para criar uma caixa de texto. Depois disso, você pode digitar o texto desejado e personalizar as configurações de fonte, tamanho, cor, etc.<br/><br/>Formas vetoriais: as formas vetoriais são desenhos que são criados usando pontos e linhas. O Photoshop possui várias ferramentas de formas vetoriais, como a ferramenta de forma livre, que permite desenhar livremente com o mouse, e a ferramenta de forma de seleção, que permite desenhar formas precisas como retângulos e elipses.<br/><br/>Formas camadas: as formas são salvos como camadas separadas, o que permite que você edite o formato e a cor independentemente da camada de imagem.<br/><br/>Formas múltiplas: você pode adicionar várias formas à sua imagem e editá-las individualmente.<br/><br/>Camadas de texto: assim como as formas, os textos são salvos como camadas separadas, o que permite que você edite o formato e a cor independentemente da camada de imagem.<br/><br/>Uma atividade para fazer é:<br/><br/>Abrir uma imagem no Photoshop<br/><br/>Criar algumas formas e textos na imagem<br/><br/>Personalizar as configurações de formato, cor e outros elementos<br/><br/>Experimentar adicionando várias formas e textos e editá-los individualmente<br/><br/>Salve a imagem como um arquivo novo.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula15: {
    nome: "15",
    titulo: "Camadas",
    conteudo: `<h5>Camadas</h5><br/>O uso de camadas é uma das principais características do Photoshop, e é possível trabalhar com múltiplas camadas em uma única imagem. Aqui estão algumas coisas que você pode aprender sobre edição de imagens com múltiplas camadas:<br/><br/>Adicionando camadas: você pode adicionar novas camadas à sua imagem usando o menu "Camadas" no topo da tela ou clicando no ícone de nova camada na barra de camadas. Isso permite que você adicione novos elementos à imagem sem afetar as camadas existentes.<br/><br/>Organizando camadas: você pode organizar as camadas na sua imagem usando a barra de camadas. Isso permite que você mova camadas para cima ou para baixo na ordem de camadas, o que afeta a forma como as camadas são exibidas.<br/><br/>Ajustando camadas: você pode ajustar as configurações de cada camada, como a opacidade, ajustando as configurações na barra de camadas. Isso permite que você controle a transparência de cada camada e crie efeitos interessantes.<br/><br/>Máscaras de camadas: as máscaras de camadas permitem que você esconda partes de uma camada, permitindo que você crie efeitos de sobreposição interessantes.<br/><br/>Camadas de ajuste: as camadas de ajuste permitem que você aplique ajustes de imagem, como ajustes de brilho e contraste, a uma camada específica, em vez de aplicá-los à imagem inteira.<br/><br/>Uma atividade para fazer é:<br/><br/>Abrir uma imagem no Photoshop<br/><br/>Adicionar várias camadas à imagem, como imagens, formas e texto<br/><br/>Organizar as camadas na ordem desejada<br/><br/>Ajustar as configurações de cada camada, como a opacidade e ajustes de brilho e contraste<br/><br/>Salve a imagem como um arquivo novo<br/><br/>Experimentar com máscaras de camadas e camadas de ajuste para criar efeitos interessantes.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula16: {
    nome: "16",
    titulo: "Impressão e Web",
    conteudo: `<h5>Impressão e Web</h5><br/>A preparação de imagens para impressão e web é um processo importante para garantir que as imagens fiquem nítidas e de alta qualidade em diferentes formatos e dispositivos. Aqui estão algumas dicas para preparar suas imagens no Photoshop:<br/><br/>Certifique-se de que sua imagem está em modo de cor correto, como CMYK para impressão ou RGB para web. Isso pode ser alterado no menu "Image" e "Mode".<br/><br/>Redimensione sua imagem para o tamanho desejado. Isso pode ser feito no menu "Image" e "Image Size". Certifique-se de que a opção "Constrain Proportions" esteja marcada para manter as proporções da imagem.<br/><br/>Aplique qualquer ajuste de brilho e contraste, recorte ou outras edições básicas de imagem necessárias.<br/><br/>Salve sua imagem como um arquivo de alta qualidade, como um arquivo JPEG ou PNG para web ou TIFF ou PDF para impressão. No menu "File" e "Save As" escolha o formato desejado.<br/><br/>Se a imagem for destinada à web, certifique-se de otimizar o tamanho do arquivo para carregamento rápido. Isso pode ser feito no menu "File" e "Save for Web"<br/><br/>Verifique a sua imagem em diferentes dispositivos e configurações de visualização para garantir que ela esteja visualmente correta.<br/><br/>Atividade:<br/><br/>Abrir uma imagem no photoshop<br/><br/>Verificar se esta na cor correta<br/><br/>Redimensionar a imagem para um tamanho desejado<br/><br/>Aplicar qualquer ajuste de brilho e contraste, recorte ou outras edições básicas de imagem necessárias<br/><br/>Salvar a imagem no formato desejado (jpg, png, tiff, pdf)<br/><br/>Otimizar o tamanho do arquivo para web<br/><br/>Verificar a imagem em diferentes dispositivos e configurações de visualização`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula17: {
    nome: "17",
    titulo: "Retoque",
    conteudo: `<h5>Retoque</h5><br/>Retoque e retoque fotográfico no Photoshop incluem ajustar a cor, iluminação e nitidez de uma imagem, remover imperfeições, adicionar ou remover elementos da imagem e criar efeitos especiais.<br/><br/>Para ajustar a cor, você pode usar ferramentas como Balanceamento de cor e Curvas. Para ajustar a iluminação, você pode usar ferramentas como Ajuste de brilho/contraste e Curvas de níveis. Para aumentar a nitidez, você pode usar a ferramenta Nitidez.<br/><br/>Para remover imperfeições, você pode usar ferramentas como Pincel de borracha, Clone Stamp e Healing Brush. Para adicionar ou remover elementos da imagem, você pode usar ferramentas como Pincel, Lasso e Magic Wand.<br/><br/>Para criar efeitos especiais, você pode usar filtros como Filtro de desfoque, Filtro de emboss e Filtro de textura.<br/><br/>Existem algumas ferramentas específicas para retoque fotográfico como o recurso de Camera raw, que permite ajustes precisos em fotos RAW, e o recurso de Liquify, que permite distorcer uma imagem para criar efeitos interessantes.<br/><br/>Atividade:<br/><br/>Escolha uma foto que você gostaria de editar e abra-a no Photoshop.<br/><br/>Use as ferramentas de ajuste de cor, iluminação e nitidez para melhorar a aparência da imagem. Experimente com ferramentas como Balanceamento de cor, Curvas, Ajuste de brilho/contraste e Nitidez.<br/><br/>Use as ferramentas de retoque para remover imperfeições, como Pincel de borracha, Clone Stamp e Healing Brush.<br/><br/>Adicione ou remova elementos da imagem usando ferramentas como Pincel, Lasso e Magic Wand.<br/><br/>Experimente com diferentes filtros para criar efeitos especiais, como Filtro de desfoque, Filtro de emboss e Filtro de textura.<br/><br/>Utilize o recurso de Camera raw para ajustar a imagem em modo RAW<br/><br/>Utilize o recurso de Liquify para distorcer a imagem e criar efeitos interessantes.<br/><br/>Salve sua edição como um novo arquivo.<br/><br/>Essa é uma atividade básica para que você possa colocar em prática os conhecimentos adquiridos sobre retoque e retoque fotográfico no Photoshop. Lembre-se de que a prática é a chave para se tornar proficiente em edição de imagens e, quanto mais você usar o software, mais fácil será para você descobrir novas técnicas e truques.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula18: {
    nome: "18",
    titulo: "Atividade",
    conteudo: `<h5>Atividade: "Retoque de Fotos Básicos"</h5><br/>Objetivo: Aprender a usar as ferramentas básicas de retoque de fotos no Photoshop.<br/><br/>Passo 1: Abra uma foto no Photoshop.<br/><br/>Passo 2: Use a ferramenta de seleção de mágico para selecionar uma área da foto que você deseja retocar.<br/><br/>Passo 3: Use a ferramenta de pincel de retoque para corrigir manchas, olheiras e outros defeitos na pele. Certifique-se de selecionar uma textura e cor semelhantes à pele ao redor da área selecionada.<br/><br/>Passo 4: Use a ferramenta de lápis para desenhar sobre a foto, adicionando ou removendo detalhes.<br/><br/>Passo 5: Use a ferramenta de borrão para suavizar áreas da foto. Certifique-se de selecionar o tamanho e a forma adequados do pincel para obter o efeito desejado.<br/><br/>Passo 6: Use a ferramenta de curva para ajustar o brilho, contraste e saturação da foto. Experimente com diferentes configurações para encontrar o equilíbrio desejado.<br/><br/>Passo 7: Salve a foto com as alterações feitas.<br/><br/>Desafio adicional: Tentar retocar uma foto de um amigo ou familiar, perguntando-lhes quais são as correções que eles gostariam de ver feitas na foto.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },
  photoshop1Aula19: {
    nome: "19",
    titulo: "Atividade",
    conteudo: `<h5>Atividade: Aprender a usar as ferramentas básicas do Photoshop</h5><br/>Abra o Photoshop e crie uma nova imagem com as configurações de sua escolha.<br/><br/>Utilize a ferramenta de seleção de mágico para selecionar uma área específica da imagem. Experimente selecionar diferentes áreas e observe como a seleção muda.<br/><br/>Utilize a ferramenta de pincel para pintar uma área selecionada. Experimente usar diferentes tamanhos de pincel e opacidades para ver como isso afeta a pintura.<br/><br/>Utilize a ferramenta de borracha para apagar uma área pintada. Experimente usar diferentes tamanhos de borracha e opacidades para ver como isso afeta a remoção de pintura.<br/><br/>Utilize a ferramenta de texto para adicionar texto à imagem. Experimente usar diferentes fontes, tamanhos e cores de texto.<br/><br/>Utilize a ferramenta de transformação para redimensionar ou distorcer uma área selecionada. Experimente usar diferentes configurações de transformação e observe como isso afeta a imagem.<br/><br/>Utilize a ferramenta de camadas para adicionar uma nova camada à imagem e experimente aplicar diferentes efeitos e filtros à camada.<br/><br/>Salve sua imagem e experimente abri-la novamente no Photoshop para ver as alterações que você fez.<br/><br/>Dica extra: Explorar as opções de "Filtro" no menu superior, onde você pode encontrar muitos efeitos interessantes para usar na sua imagem.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 17,
  },

  photoshop2Aula1: {
    nome: "1",
    titulo: "Edição avançada",
    conteudo: `Aprender edição avançada de imagens com o Photoshop requer prática e paciência. Aqui estão algumas dicas para começar:<br/><br/>Remoção de objetos: Utilize ferramentas como a ferramenta de recorte, a varinha mágica ou a ferramenta de pincel para remover objetos indesejados de sua imagem.<br/><br/>Substituição de cores: Use a ferramenta de seleção de cores ou a camada de máscara de cor para selecionar uma área específica de sua imagem e mudar sua cor.<br/><br/>Ajuste de brilho e contraste: Ajuste o brilho e o contraste de sua imagem usando camadas de ajuste ou ajustes locais.<br/><br/>Técnicas de composição: Aprenda a combinar várias imagens em uma única imagem para criar composições avançadas.<br/><br/>Ferramentas de retoque: Aprenda a usar ferramentas de retoque, como a ferramenta de clonagem e a ferramenta de pincel, para melhorar a aparência de sua imagem.<br/><br/>Estas são apenas algumas dicas para começar a aprender edição avançada de imagens com o Photoshop. É importante praticar frequentemente para melhorar suas habilidades.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula2: {
    nome: "2",
    titulo: "Atividade",
    conteudo: `Atividade: Remoção de objetos indesejados<br/><br/>Passo 1: Escolha uma imagem com um objeto indesejado que você gostaria de remover.<br/><br/>Passo 2: Abra a imagem no Photoshop e selecione a ferramenta de recorte ou a varinha mágica.<br/><br/>Passo 3: Use a ferramenta para selecionar o objeto indesejado e pressione "Delete" ou "Backspace" para excluí-lo.<br/><br/>Passo 4: Se o objeto não for removido completamente, use a ferramenta de pincel para ajudar a cobrir a área com a cor do fundo.<br/><br/>Passo 5: Verifique a imagem e ajuste-a conforme necessário. Salve sua imagem final.<br/><br/>Pratique esta técnica com várias imagens diferentes até se sentir confortável com ela. Em seguida, experimente as outras técnicas avançadas de edição de imagem. Lembre-se de que a prática é a chave para melhorar suas habilidades.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula3: {
    nome: "3",
    titulo: "Substituição de cores",
    conteudo: `A substituição de cores no Photoshop é uma técnica avançada que permite mudar a cor de uma área específica de uma imagem. Aqui está um passo a passo para substituir cores:<br/><br/>Passo 1: Abra a imagem que você gostaria de mudar a cor em seu Photoshop.<br/><br/>Passo 2: Selecione a ferramenta de seleção de cores ou crie uma camada de máscara de cor. A ferramenta de seleção de cores permite selecionar uma cor específica na imagem, enquanto a camada de máscara de cor permite escolher uma área específica para mudar a cor.<br/><br/>Passo 3: Depois de selecionar a área que você gostaria de mudar a cor, clique no botão "Color Balance" na barra de ferramentas. Isso abrirá uma janela de diálogo onde você pode mudar as configurações de brilho, saturação e tonalidade.<br/><br/>Passo 4: Use as opções de cor para mudar a cor da área selecionada da imagem. Quando estiver satisfeito com o resultado, clique em "OK".<br/><br/>Passo 5: Verifique a imagem para garantir que a cor substituída esteja de acordo com as suas expectativas. Se necessário, ajuste a seleção de cores ou a camada de máscara de cor.<br/><br/>Passo 6: Salve a sua imagem final.<br/><br/>Lembre-se de que a substituição de cores é uma técnica avançada que requer prática para dominar. Pratique com várias imagens até se sentir confortável com a técnica.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula4: {
    nome: "4",
    titulo: "Atividade",
    conteudo: `Atividade: Substituição de Cores no Photoshop<br/><br/>Objetivo: Praticar a substituição de cores em imagens no Photoshop.<br/><br/>Material: Adobe Photoshop.<br/><br/>Instruções:<br/><br/>Escolha uma imagem que você gostaria de mudar a cor.<br/><br/>Siga os passos descritos acima para mudar a cor de uma área específica da imagem.<br/><br/>Experimente mudar as cores em diferentes áreas da imagem para melhorar suas habilidades.<br/><br/>Salve as imagens finais em formatos diferentes e compare o resultado com a imagem original.<br/><br/>Repita o processo com várias imagens diferentes para se tornar mais habilidoso na substituição de cores no Photoshop.<br/><br/>Boa sorte e divirta-se!`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula5: {
    nome: "5",
    titulo: "Brilho e contraste",
    conteudo: `Ajuste de brilho e contraste em imagens é uma técnica comum que permite melhorar a aparência geral de uma imagem. Aqui está um resumo de como ajustar o brilho e contraste no Photoshop:<br/><br/>Abra a imagem que você gostaria de ajustar no Photoshop.<br/><br/>Vá para a guia "Camadas" e clique em "Nova camada de ajuste". Isso adicionará uma nova camada de ajuste à sua imagem.<br/><br/>Selecione a camada de ajuste e vá para o menu "Imagem" na barra de ferramentas. Selecione "Ajustes" e, em seguida, "Brilho/Contraste".<br/><br/>Use as opções de brilho e contraste na janela de diálogo para ajustar as configurações de acordo com as suas necessidades. Você pode usar os deslizadores ou digitar valores específicos.<br/><br/>Clique em "OK" para aplicar as alterações. Se necessário, ajuste novamente a camada de ajuste até obter o resultado desejado.<br/><br/>Salve a sua imagem final.<br/><br/>Lembre-se de que ajustar o brilho e contraste é uma técnica simples, mas pode fazer uma grande diferença na aparência de sua imagem. Experimente com diferentes configurações até encontrar o equilíbrio certo para a sua imagem.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula6: {
    nome: "6",
    titulo: "Composição",
    conteudo: `Composição é a arte de combinar várias imagens em uma única imagem para criar uma nova narrativa ou mensagem. Aqui estão algumas técnicas de composição que você pode aprender e aplicar no Photoshop:<br/><br/>Regra dos terços: divida a imagem em três partes iguais e coloque os elementos importantes nas linhas ou nas interseções dessas linhas para criar equilíbrio e harmonia.<br/><br/>Ponto de fuga: use uma linha ou uma estrutura para guiar o olho do espectador através da imagem e para um ponto de interesse importante.<br/><br/>Criação de profundidade: use técnicas de perspectiva, escala e sobreposição para dar a impressão de profundidade e dimensão à sua composição.<br/><br/>Contraste de cor: use contraste de cor para destacar elementos importantes na imagem e para criar uma sensação de equilíbrio e harmonia.<br/><br/>Criação de narrativa: use elementos visuais, como formas, cores e texto, para contar uma história ou transmitir uma mensagem.<br/><br/>Lembre-se de que a composição é uma arte e, assim como qualquer outra arte, requer prática e experimentação para dominar. Pratique com várias imagens e técnicas até se sentir confortável com suas habilidades de composição.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula7: {
    nome: "7",
    titulo: "Ferramentas de retoque",
    conteudo: `As ferramentas de retoque no Photoshop são usadas para corrigir pequenos problemas ou melhorar a aparência de uma imagem. Aqui estão algumas dicas para usar as ferramentas de retoque:<br/><br/>Ferramenta de clonagem: A ferramenta de clonagem permite copiar pixels de uma área de uma imagem para outra. Isso é útil para remover manchas ou objetos indesejados.<br/><br/>Ferramenta de pincel: A ferramenta de pincel permite pintar sobre a imagem, como se você estivesse pintando com um pincel de verdade. Isso é útil para corrigir pequenos problemas, como manchas ou manchas.<br/><br/>Camadas de máscara: Quando você usa a ferramenta de clonagem ou a ferramenta de pincel, é importante usar camadas de máscara para controlar a aplicação da ferramenta. Isso permite que você tenha mais controle sobre as alterações e possa desfazê-las se necessário.<br/><br/>Ajustes locais: Algumas ferramentas de retoque, como a ferramenta de pincel, permitem ajustar o brilho e o contraste em uma área específica da imagem. Isso é útil para corrigir problemas de iluminação ou outros problemas locais.<br/><br/>Lembre-se de que o retoque de imagens é uma técnica avançada e requer prática para dominar. Pratique com várias imagens até se sentir confortável com as ferramentas.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula8: {
    nome: "8",
    titulo: "Atividade",
    conteudo: `Atividade: Correção de manchas na imagem<br/><br/>Abra uma imagem no Photoshop que contenha uma mancha ou objeto indesejado que você gostaria de remover.<br/><br/>Selecione a ferramenta de clonagem e selecione a área da imagem que você deseja copiar.<br/><br/>Pressione e mantenha pressionada a tecla Alt e clique na área da imagem que você deseja retocar.<br/><br/>Solte a tecla Alt e clique e arraste o cursor para cima e para baixo na área que você deseja retocar. Isso irá copiar pixels da área selecionada para a área que você está retocando.<br/><br/>Repita o processo até que a mancha ou objeto indesejado seja removido.<br/><br/>Salve a imagem e compare-a com a imagem original.<br/><br/>Observação: você pode querer usar a ferramenta de pincel para ajustar a cor e a textura da área retocada para que fique mais harmoniosa com o resto da imagem.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula9: {
    nome: "9",
    titulo: "Efeitos",
    conteudo: `A criação de efeitos no Photoshop é uma técnica que permite adicionar realismo e profundidade às suas imagens. Aqui estão algumas dicas para criar efeitos no Photoshop:<br/><br/>Iluminação: Para criar iluminação realista, experimente usar camadas de luz e sombra, ajustar o brilho e o contraste, e usar ferramentas de iluminação como a ferramenta de pincel de luz.<br/><br/>Sombras: Para criar sombras realistas, experimente usar camadas de sombra, ajustar o brilho e o contraste, e usar ferramentas de sombra como a ferramenta de pincel de sombra.<br/><br/>Reflexos: Para criar reflexos realistas, experimente usar camadas de reflexo, ajustar o brilho e o contraste, e usar ferramentas de reflexo como a ferramenta de pincel de reflexo.<br/><br/>Lembre-se de que a criação de efeitos é uma técnica avançada e requer prática para dominar. Pratique com várias imagens até se sentir confortável com as ferramentas.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula10: {
    nome: "10",
    titulo: "Seleçao de Ferramentes e Camadas",
    conteudo: `<h5>Seleçao de Ferramentes e Camadas</h5><br/>Selecionar ferramentas e camadas no Photoshop é essencial para trabalhar com suas imagens.<br/><br/>Para selecionar uma ferramenta, você pode clicar na ferramenta desejada na barra lateral esquerda da tela ou usar as teclas de atalho correspondentes. Também é possível selecionar ferramentas clicando e mantendo pressionado o botão esquerdo do mouse sobre a ferramenta atual, o que exibirá uma lista de ferramentas relacionadas.<br/><br/>Para selecionar uma camada, você pode clicar na camada desejada na janela Camadas na parte direita da tela. Também é possível selecionar várias camadas de uma só vez pressionando a tecla Ctrl enquanto clica nas camadas desejadas.<br/><br/>Você também pode selecionar camadas utilizando a ferramenta de seleção de camadas, que é representada por um ícone de mão com um ponto de exclamação. Com essa ferramenta, é possível selecionar camadas clicando nelas na tela de trabalho.<br/><br/>É importante notar que ao selecionar uma camada, todas as edições serão feitas apenas na camada selecionada, permitindo que você trabalhe com camadas individuais sem afetar as outras.<br/><br/>Uma atividade para se fazer é:<br/><br/>Abrir uma imagem no Photoshop<br/><br/>Adicionar algumas camadas extras, como textos e formas<br/><br/>Testar as diferentes ferramentas de seleção de camadas e ferramentas para entender como elas funcionam<br/><br/>Experimentar trabalhar com as camadas selecionadas, movendo-as, redimensionando-as, aplicando filtros, etc.<br/><br/>Salvar a imagem e comparar com a original.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },

  photoshop2Aula11: {
    nome: "11",
    titulo: "Seleção avançada",
    conteudo: `A seleção avançada no Photoshop permite selecionar partes específicas da imagem com precisão, o que é útil para retoques e edições. Aqui estão algumas dicas para aprender técnicas avançadas de seleção:<br/><br/>Seleção baseada em canais: A seleção baseada em canais permite selecionar partes da imagem com base nas informações de cor. É uma técnica útil para selecionar partes da imagem com fundos uniformes.<br/><br/>Máscaras de camada: As máscaras de camada permitem controlar a visibilidade de uma camada. Isso é útil para selecionar partes da imagem sem afetar outras partes.<br/><br/>Ferramenta de seleção de contorno: A ferramenta de seleção de contorno permite selecionar partes da imagem com base nos contornos. É uma técnica útil para selecionar objetos com bordas bem definidas.<br/><br/>Lembre-se de que a seleção avançada é uma técnica avançada e requer prática para dominar. Pratique com várias imagens até se sentir confortável com as ferramentas.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula12: {
    nome: "12",
    titulo: "Atividade",
    conteudo: `Atividade prática:<br/><br/>Escolha uma imagem com uma área uniforme de fundo para experimentar a seleção baseada em canais.<br/><br/>Abra a imagem no Photoshop e selecione a ferramenta de seleção baseada em canais.<br/><br/>Escolha um canal que represente o fundo uniforme e aplique a seleção.<br/><br/>Verifique se a seleção está correta e ajuste, se necessário.<br/><br/>Crie uma nova camada e aplique uma cor de fundo diferente para ver o resultado da seleção.<br/><br/>Repita os passos acima para experimentar as outras técnicas de seleção avançada, como máscaras de camada e ferramenta de seleção de contorno.<br/><br/>Pratique com várias imagens até se sentir confortável com as ferramentas e técnicas de seleção avançada.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula13: {
    nome: "13",
    titulo: "Filtros e Efeitos",
    conteudo: `Camadas e máscaras são elementos-chave do Photoshop e permitem a você controlar a visibilidade de diferentes partes de uma imagem. Aqui estão algumas dicas para aprender a utilizar camadas e máscaras de forma avançada:<br/><br/>Camadas: Uma imagem no Photoshop pode ser composta por várias camadas, cada uma com seus próprios elementos gráficos. Isso permite que você trabalhe em diferentes partes da imagem de forma independente e ajuste a visibilidade de cada camada.<br/><br/>Máscaras de camada: Uma máscara de camada é uma camada adicional que controla a visibilidade de outra camada. Você pode usar máscaras de camada para controlar a transparência de uma camada, para remover partes da imagem ou para aplicar efeitos a partes específicas da imagem.<br/><br/>Ferramentas de máscaras: O Photoshop possui várias ferramentas para criar e editar máscaras, como a ferramenta Pincel, a ferramenta Varinha Mágica e a ferramenta Seleção de Camada. Essas ferramentas permitem selecionar partes da imagem para aplicar máscaras e controlar a visibilidade de camadas.<br/><br/>Lembre-se de que trabalhar com camadas e máscaras é uma técnica avançada e requer prática para dominar. Pratique com várias imagens até se sentir confortável com as ferramentas.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula14: {
    nome: "14",
    titulo: "Atividade",
    conteudo: `Atividade sobre camadas e máscaras:<br/><br/>Abra uma imagem no Photoshop e crie uma nova camada.<br/><br/>Adicione um elemento gráfico, como um retângulo, a essa nova camada.<br/><br/>Crie uma máscara de camada para controlar a visibilidade desse elemento gráfico.<br/><br/>Experimente usar diferentes ferramentas de máscaras, como a ferramenta Pincel e a ferramenta Varinha Mágica, para editar a máscara.<br/><br/>Tente adicionar mais camadas e máscaras para a imagem e experimente ajustar a visibilidade de cada camada para ver o resultado final.<br/><br/>Com a prática, você poderá controlar a visibilidade de diferentes partes da imagem de forma avançada com camadas e máscaras no Photoshop.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula15: {
    nome: "15",
    titulo: "Retoque",
    conteudo: `Retoque de fotografias é o processo de correção ou melhoria de uma imagem fotográfica. Aqui estão algumas dicas para aprender técnicas avançadas de retoque de fotografias no Photoshop:<br/><br/>Remoção de rugas e manchas: A ferramenta Pincel de Escova é útil para remover rugas e manchas da pele. É possível ajustar a cor e a opacidade da escova para corresponder ao tom da pele e aplicar a cor de forma suave.<br/><br/>Correção de olhos vermelhos: A ferramenta Pincel de Escova também é útil para corrigir olhos vermelhos. É possível selecionar a área dos olhos e aplicar uma cor de correção para remover o vermelho.<br/><br/>Melhoria de textura e cor: A ferramenta Varinha Mágica é útil para selecionar áreas específicas da imagem, enquanto a ferramenta Pincel de Escova pode ser usada para aplicar filtros e efeitos para melhorar a textura e a cor da pele.<br/><br/>Lembre-se de que o retoque de fotografias é uma técnica avançada e requer prática para dominar. É importante praticar com várias imagens e ajustar as ferramentas de acordo com as necessidades de cada imagem. Além disso, é importante lembrar de não exagerar no retoque, a fim de preservar a naturalidade da imagem.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula16: {
    nome: "16",
    titulo: "Atividade",
    conteudo: `Faça o seguinte exercício para praticar suas habilidades de retoque de fotografias:<br/><br/>Escolha uma imagem que você gostaria de retocar.<br/><br/>Utilize a ferramenta Varinha Mágica para selecionar a pele da imagem.<br/><br/>Ajuste a cor da pele usando a ferramenta Balanceamento de Cores.<br/><br/>Use a ferramenta Pincel de Escova para remover rugas e manchas da pele, ajustando a cor e opacidade da escova para corresponder ao tom da pele.<br/><br/>Use a ferramenta Pincel de Escova para corrigir olhos vermelhos, aplicando uma cor de correção.<br/><br/>Aplique filtros e efeitos para melhorar a textura e a cor da pele.<br/><br/>Salve a sua imagem retocada e compare com a original para ver sua evolução.<br/><br/>Lembre-se de praticar regularmente e não exagerar no retoque para preservar a naturalidade da imagem. Boa sorte!`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },
  photoshop2Aula17: {
    nome: "17",
    titulo: "Ilustrações",
    conteudo: `Criação de ilustrações é o processo de criar imagens que ilustram ou representam algo. Aqui estão algumas dicas para aprender a criar ilustrações no Photoshop:<br/><br/>Ferramentas de desenho: O Photoshop possui uma série de ferramentas de desenho, incluindo a ferramenta Pincel, a ferramenta Lápis e a ferramenta Forma. Essas ferramentas permitem criar formas e linhas que podem ser usadas para criar ilustrações.<br/><br/>Formas e camadas: É possível criar formas no Photoshop usando ferramentas de desenho e, em seguida, ajustar as propriedades de cor, opacidade e estilo de borda dessas formas. Além disso, é possível criar camadas separadas para cada forma ou elemento da ilustração, permitindo ajustar a visibilidade de cada parte da ilustração independentemente.<br/><br/>Efeitos e filtros: O Photoshop possui uma ampla variedade de efeitos e filtros que podem ser aplicados a camadas ou formas para criar efeitos visuais. É possível experimentar com diferentes efeitos e filtros para encontrar o estilo desejado para sua ilustração.<br/><br/>Lembre-se de que a criação de ilustrações é uma habilidade que requer prática e experimentação. É importante praticar com várias ferramentas e efeitos para desenvolver suas habilidades de criação de ilustrações. Além disso, é importante estudar o trabalho de outros artistas para se inspirar e desenvolver sua própria voz e estilo.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 18,
  },

  photoshop3Aula1: {
    nome: "1",
    titulo: "Edição avançada",
    conteudo: `A edição avançada de imagens e fotos no Photoshop é o processo de modificar imagens para corrigir problemas, aprimorar a aparência ou criar efeitos especiais. Algumas técnicas comuns incluem:<br/><br/>Correção de cor: É possível corrigir a cor de uma imagem, incluindo o brilho, o contraste e a saturação, para melhorar a aparência geral da imagem.<br/><br/>Remoção de objetos indesejados: É possível remover objetos indesejados da imagem, como manchas, linhas ou pessoas, usando ferramentas como a ferramenta Pincel de Restauração ou a ferramenta Borracha.<br/><br/>Adição de camadas: É possível adicionar camadas à imagem para criar efeitos especiais ou para combinar elementos de várias imagens.<br/><br/>Ajuste de perspectiva: É possível ajustar a perspectiva da imagem para corrigir problemas como a distorção ou o encurvamento da imagem.<br/><br/>Ajuste de luz e sombra: É possível ajustar a luz e as sombras da imagem para melhorar a aparência e criar efeitos dramáticos.<br/><br/>Lembre-se de que a edição avançada de imagens e fotos requer habilidade e paciência. É importante praticar com várias ferramentas e técnicas para desenvolver suas habilidades e criar resultados impressionantes.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula2: {
    nome: "2",
    titulo: "Atividade",
    conteudo: `Atividade: Correção de cor em uma imagem<br/><br/>Passo 1: Abra uma imagem em que você gostaria de corrigir a cor no Photoshop.<br/><br/>Passo 2: Selecione a camada da imagem que você gostaria de editar. Caso a imagem tenha várias camadas, certifique-se de selecionar a camada correta antes de começar a correção de cor.<br/><br/>Passo 3: Vá para o menu "Imagem" e clique em "Ajustes". Escolha "Brilho/Contraste" ou "Saturação" dependendo do tipo de correção de cor que você deseja fazer.<br/><br/>Passo 4: Use as barras de ajuste para aumentar ou diminuir o brilho, contraste e/ou saturação da imagem, conforme desejado. Observe as mudanças na imagem ao alterar os valores.<br/><br/>Passo 5: Uma vez que você esteja satisfeito com as alterações, clique em "Ok" para aplicar as mudanças.<br/><br/>Passo 6: Caso deseje fazer mais ajustes, repita os passos 3 a 5.<br/><br/>Lembre-se de que a correção de cor é uma tarefa subjetiva, então é importante experimentar diferentes configurações para encontrar a que melhor se adapta às suas necessidades e gostos pessoais.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula3: {
    nome: "3",
    titulo: "Atividade",
    conteudo: `Atividade: Remoção de objetos indesejados com o Photoshop<br/><br/>Passo 1: Abra a imagem no Photoshop e crie uma camada de trabalho separada para a edição.<br/><br/>Passo 2: Selecione a ferramenta Pincel de Restauração ou a ferramenta Borracha e comece a apagar o objeto indesejado. É importante ser cuidadoso ao escolher o tamanho da ferramenta para evitar remover partes da imagem que você deseja preservar.<br/><br/>Passo 3: Para objetos mais complicados, como pessoas ou animais, você pode precisar selecionar a área ao redor do objeto antes de apagá-lo. Para fazer isso, use a ferramenta Lasso ou a ferramenta Varinha Mágica.<br/><br/>Passo 4: Quando terminar de apagar o objeto indesejado, você pode ajustar a imagem original para preencher as áreas vazias. Isso pode ser feito com a ferramenta Pincel de Preenchimento ou a ferramenta Clone Stamp.<br/><br/>Passo 5: Salve sua imagem editada.<br/><br/>Lembre-se de que remover objetos indesejados pode ser um processo demorado e requer habilidade e paciência. É importante praticar com várias imagens para desenvolver suas habilidades de edição.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula4: {
    nome: "4",
    titulo: "Atividade",
    conteudo: `Atividade: Remoção de objetos indesejados com o Photoshop<br/><br/>Passo 1: Abra a imagem no Photoshop e crie uma camada de trabalho separada para a edição.<br/><br/>Passo 2: Selecione a ferramenta Pincel de Restauração ou a ferramenta Borracha e comece a apagar o objeto indesejado. É importante ser cuidadoso ao escolher o tamanho da ferramenta para evitar remover partes da imagem que você deseja preservar.<br/><br/>Passo 3: Para objetos mais complicados, como pessoas ou animais, você pode precisar selecionar a área ao redor do objeto antes de apagá-lo. Para fazer isso, use a ferramenta Lasso ou a ferramenta Varinha Mágica.<br/><br/>Passo 4: Quando terminar de apagar o objeto indesejado, você pode ajustar a imagem original para preencher as áreas vazias. Isso pode ser feito com a ferramenta Pincel de Preenchimento ou a ferramenta Clone Stamp.<br/><br/>Passo 5: Salve sua imagem editada.<br/><br/>Lembre-se de que remover objetos indesejados pode ser um processo demorado e requer habilidade e paciência. É importante praticar com várias imagens para desenvolver suas habilidades de edição.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula5: {
    nome: "5",
    titulo: "Atividade",
    conteudo: `Atividade: Adicionando camadas em uma imagem no Photoshop<br/><br/>Passo 1: Abra a imagem que deseja editar no Photoshop.<br/><br/>Passo 2: Clique no ícone "Camada" na barra de ferramentas do lado direito da tela e selecione "Nova Camada" na lista de opções. Uma nova camada aparecerá na lista de camadas no painel de camadas.<br/><br/>Passo 3: Escolha a ferramenta que deseja usar para adicionar o elemento à nova camada, como a ferramenta Pincel, a ferramenta Lápis ou a ferramenta Forma.<br/><br/>Passo 4: Desenhe ou adicione o elemento que deseja na nova camada.<br/><br/>Passo 5: Ajuste as propriedades da camada, como cor, opacidade e estilo de borda, se desejar.<br/><br/>Passo 6: Repita os passos 2 a 5 para adicionar mais camadas e combinar elementos de várias imagens.<br/><br/>Passo 7: Salve sua imagem editada clicando em "Arquivo" e depois em "Salvar como".<br/><br/>Lembre-se de que adicionar camadas é uma técnica avançada de edição de imagens e pode levar algum tempo para dominar. É importante praticar e experimentar com diferentes ferramentas e efeitos para desenvolver suas habilidades.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula6: {
    nome: "6",
    titulo: "Atividade",
    conteudo: `Atividade: Correção de perspectiva em uma imagem<br/><br/>Material necessário: um computador com o Adobe Photoshop instalado<br/><br/>Passo 1: Abra a imagem desejada no Photoshop e selecione a ferramenta "Distorção de perspectiva" na barra de ferramentas.<br/><br/>Passo 2: Clique e arraste os pontos de controle nas bordas da imagem para corrigir a perspectiva.<br/><br/>Passo 3: Visualize a imagem e ajuste mais se necessário.<br/><br/>Passo 4: Salve a imagem corrigida clicando em "Arquivo" e selecionando "Salvar como".<br/><br/>Lembre-se de sempre fazer backup da imagem original antes de realizar ajustes significativos. É importante experimentar com diferentes ferramentas e técnicas de correção de perspectiva até encontrar a melhor solução para cada imagem.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula7: {
    nome: "7",
    titulo: "Atividade",
    conteudo: `Atividade: Ajuste de luz e sombra em uma imagem<br/><br/>Passo 1: Abra sua imagem no Photoshop.<br/><br/>Passo 2: Crie uma camada de ajuste de níveis. Isso permitirá ajustar a luz e as sombras na imagem.<br/><br/>Passo 3: Ajuste os controles de níveis para aumentar ou diminuir a quantidade de luz e sombra na imagem. Tente equilibrar a imagem, de modo que não haja áreas muito claras ou muito escuras.<br/><br/>Passo 4: Se desejar, adicione uma camada de correção de tonalidade/saturação para ajustar a cor na imagem.<br/><br/>Passo 5: Se ainda precisar de mais ajuste, experimente usar outras ferramentas de ajuste de cor, como a ferramenta Curva.<br/><br/>Passo 6: Quando estiver satisfeito com o resultado, salve sua imagem.<br/><br/>Lembre-se de que o ajuste de luz e sombra é uma técnica avançada e pode requerer algum tempo e prática para dominar. Não tenha medo de experimentar diferentes ajustes e configurações para encontrar o melhor resultado para sua imagem.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula8: {
    nome: "8",
    titulo: "Camadas e máscaras",
    conteudo: `Uso avançado de camadas e máscaras: O uso avançado de camadas e máscaras no Photoshop permite a você criar imagens complexas e efeitos sofisticados. Aqui estão algumas dicas para ajudá-lo a aperfeiçoar suas habilidades em camadas e máscaras:<br/><br/>Camadas: É importante entender como usar camadas para organizar sua imagem e controlar a visibilidade de cada elemento. É possível criar camadas para cada elemento da imagem e ajustar sua opacidade e estilo de mistura.<br/><br/>Máscaras de camada: As máscaras de camada permitem que você selecione ou oculte partes da camada, o que é útil para ajustar ou corrigir partes da imagem sem afetar outras áreas.<br/><br/>Blend Modes: Os modos de mistura permitem que você controle como as camadas interagem umas com as outras, criando efeitos dramáticos e sofisticados.<br/><br/>Ajuste de camadas: É possível aplicar ajustes em camadas específicas, como correção de cor ou ajuste de brilho, sem afetar outras camadas na imagem.<br/><br/>Combinação de camadas: É possível combinar camadas para criar efeitos especiais ou para unir elementos de várias imagens.<br/><br/>Lembre-se de que o uso avançado de camadas e máscaras requer prática e experimentação. É importante experimentar com diferentes opções e combinações para desenvolver suas habilidades em camadas e máscaras.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula9: {
    nome: "9",
    titulo: "Atividade",
    conteudo: `Atividade:<br/><br/>Abra uma imagem no Photoshop e crie três camadas separadas para cada elemento da imagem (por exemplo, fundo, objeto principal e elementos adicionais).<br/><br/>Ajuste a opacidade e o estilo de mistura de cada camada para controlar a visibilidade de cada elemento.<br/><br/>Use a ferramenta de máscara de camada para selecionar ou ocultar partes de uma camada. Por exemplo, se você quiser remover um objeto indesejado da camada do objeto principal, use a ferramenta de máscara de camada para ocultar essa parte da camada.<br/><br/>Experimente com diferentes modos de mistura para ver como eles afetam as camadas na imagem.<br/><br/>Aplique ajustes em uma camada específica (como correção de cor ou ajuste de brilho) e veja como eles afetam apenas essa camada e não as outras.<br/><br/>Finalmente, combine as camadas para criar uma imagem final.<br/><br/>Lembre-se de salvar a imagem em um formato que permita edições futuras, como o formato de arquivo PSD do Photoshop.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula10: {
    nome: "10",
    titulo: "Efeitos e filtros",
    conteudo: `A criação de efeitos e filtros personalizados em programas de edição de imagem, como o Photoshop, permite que você crie soluções exclusivas e altamente personalizadas para suas necessidades de edição de imagem. Algumas dicas para criar efeitos e filtros personalizados incluem:<br/><br/>Usar camadas e máscaras: As camadas e máscaras são ferramentas-chave para a criação de efeitos personalizados. Você pode usar camadas para aplicar efeitos a diferentes elementos da imagem, enquanto as máscaras permitem que você selecione ou oculte partes da camada.<br/><br/>Utilizar ferramentas de desenho: Ferramentas de desenho, como pincéis, lápis e formas, são úteis para criar elementos personalizados e aplicar efeitos a eles.<br/><br/>Explorar blend modes: Os modos de mistura permitem que você controle como as camadas interagem umas com as outras, criando efeitos dramáticos e sofisticados.<br/><br/>Experimentar com ajustes: Ajustes, como correção de cor, brilho e contraste, são ferramentas-chave para a criação de efeitos personalizados. Experimente diferentes combinações de ajustes para encontrar o resultado desejado.<br/><br/>Salvar como ação: Depois de criar um efeito ou filtro personalizado, você pode salvar como uma ação para uso futuro. Isso economiza tempo e permite que você aplique facilmente o efeito a outras imagens.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },

  photoshop3Aula11: {
    nome: "11",
    titulo: "Integração",
    conteudo: `A integração entre o Photoshop e outras ferramentas de design, como Illustrator e InDesign, é útil para criar trabalhos completos e sofisticados. Aqui estão algumas coisas que você pode fazer com essa integração:<br/><br/>Importar imagens do Photoshop para o Illustrator ou InDesign: É possível importar imagens editadas no Photoshop para o Illustrator ou InDesign, onde elas podem ser usadas em projetos de design gráfico.<br/><br/>Exportar do Illustrator ou InDesign para o Photoshop: É possível exportar arquivos do Illustrator ou InDesign para o Photoshop, onde eles podem ser editados em detalhes.<br/><br/>Trabalhar com camadas: É possível importar camadas do Photoshop para o Illustrator ou InDesign, onde elas podem ser editadas e organizadas de acordo com suas necessidades.<br/><br/>Uso de fontes e estilos: É possível usar fontes e estilos padrão do Illustrator ou InDesign no Photoshop, e vice-versa, para garantir uma aparência consistente em todo o projeto.<br/><br/>Edição de elementos gráficos: É possível editar elementos gráficos criados no Illustrator ou InDesign no Photoshop, para ajustar sua aparência e cor.<br/><br/>Em resumo, a integração entre o Photoshop, Illustrator e InDesign permite aos designers criar trabalhos completos e sofisticados, combinando habilidades de edição de imagem, design gráfico e layout.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula12: {
    nome: "12",
    titulo: "Automatização",
    conteudo: `A automatização de tarefas no Photoshop é uma das formas mais eficientes de poupar tempo e garantir a consistência na edição de imagens. Algumas das tarefas que você pode automatizar incluem:<br/><br/>Aplicação de filtros: é possível criar uma ação para aplicar um determinado filtro a uma imagem e, em seguida, aplicá-lo automaticamente a várias imagens ao mesmo tempo.<br/><br/>Ajustes em lote: você pode criar uma ação para ajustar o brilho, o contraste e a saturação de uma imagem e, em seguida, aplicá-la automaticamente a várias imagens ao mesmo tempo.<br/><br/>Processamento em lote: você pode criar uma ação que inclua várias etapas de edição, como redimensionamento, renomeação e salvamento, e aplicá-la automaticamente a várias imagens.<br/><br/>Processamento de imagem em lote: você pode usar o recurso de processamento de imagem em lote para aplicar ações e scripts a um conjunto de imagens ao mesmo tempo.<br/><br/>Para automatizar tarefas no Photoshop, você precisará aprender como criar ações e aplicá-las em lote. Além disso, é importante compreender a lógica por trás do processo de automação para que você possa criar ações personalizadas que atendam às suas necessidades específicas.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
  photoshop3Aula13: {
    nome: "13",
    titulo: "Filtros e Efeitos",
    conteudo: `Atividade: Automatização de tarefas no Photoshop<br/><br/>Escolha uma tarefa repetitiva que você realiza frequentemente no Photoshop, como aplicar um filtro específico ou ajustar o brilho, contraste e saturação de uma imagem.<br/><br/>Acesse a janela de Ações e clique no botão "Nova Ação".<br/><br/>Dê um nome à sua ação e clique no botão "Gravar".<br/><br/>Realize a tarefa que você escolheu, como aplicar um filtro ou ajustar o brilho, contraste e saturação.<br/><br/>Pare a gravação da ação clicando no botão "Parar".<br/><br/>Salve sua ação.<br/><br/>Escolha uma pasta com imagens que você deseja processar e selecione "Processar em lote" na opção Automatização.<br/><br/>Selecione a ação que você criou e configure as opções de saída.<br/><br/>Clique no botão "Iniciar" para processar as imagens em lote.<br/><br/>Verifique os resultados e ajuste sua ação se necessário.<br/><br/>Com a automatização de tarefas, você pode poupar tempo e garantir a consistência na edição de imagens. É importante experimentar e ajustar suas ações de acordo com suas necessidades específicas.`,
    video: "https://www.youtube.com/embed/ilwewVTh1R4",
    cursoId: 20,
  },
};
