module.exports = {
    ppoint1 : {
        nome: 'PowerPoint Básico',
        professor: 'Jonathan Franzen Fagundes',
        descricao: 'Curso de PowerPoint iniciante',
        conquista: 'Editor de Apresentaçoes',
        titulo: 'PowerPoint', 
        tier: '1', 
        image: 'powerpoint.png'
    },
    ppoint2 : {
        nome: 'PowerPoint Intermediario', 
        professor: 'Jonathan Franzen Fagundes', 
        descricao: 'Curso de PowerPoint Intermediario', 
        conquista: 'Editor de Apresentaçoes Profisisonal', 
        titulo: 'PowerPoint', 
        tier: '2', 
        image: 'powerpoint.png'
    },
    ppoint3 : {
        nome: 'PowerPoint Avançado', 
        professor: 'Jonathan Franzen Fagundes', 
        descricao: 'Curso de PowerPoint Avançado', 
        conquista: 'Mestre em Ediçao de Apresentaçoes', 
        titulo: 'PowerPoint', 
        tier: 'MAX', 
        image: 'powerpoint.png'
    },

    ppoint1Aula1 : { 
        nome: '1', 
        titulo: 'Introduçao ao Microsoft PowerPoint', 
        conteudo: `O PowerPoint é um programa de apresentação da Microsoft que permite criar apresentações de slides com texto, imagens, gráficos, vídeos e outros elementos multimídia. Ele é amplamente utilizado em ambientes de negócios, educação e entretenimento para comunicar ideias de maneira visual e atraente.<br/><br/>Aqui estão alguns conceitos básicos e dicas para começar a usar o PowerPoint:<br/><br/>Interface do programa: Ao abrir o PowerPoint, você verá uma janela com uma série de guias na parte superior, incluindo "Início", "Layout", "Transições" e "Animar". Essas guias fornecem acesso às ferramentas e recursos do programa. Na parte esquerda da tela, você encontrará o "Painel de tarefas" que fornece acesso às opções de layout, estilo e formatação.<br/><br/>Criando uma nova apresentação: Para criar uma nova apresentação, você pode selecionar "Novo" na tela inicial ou clicar em "Arquivo" e "Novo" no menu superior. Em seguida, você pode escolher um modelo pré-projetado ou criar uma apresentação em branco.<br/><br/>Adicionando slides: Para adicionar novos slides à sua apresentação, você pode clicar no botão "Novo slide" na guia "Início" ou selecionar "Novo slide" no menu do botão direito do mouse. Existem vários tipos de slides disponíveis, como títulos, conteúdo, comparação, tópicos e muito mais.<br/><br/>Adicionando conteúdo: Depois de criar seus slides, você pode adicionar conteúdo, como texto, imagens, gráficos e vídeos, usando as ferramentas na guia "Início" e no painel de tarefas. É possível formatar o texto, adicionar efeitos e transições, e personalizar a aparência da apresentação.<br/><br/>Salvando e compartilhando: Quando terminar sua apresentação, você pode salvar e compartilhar com outros usando as opções de "Arquivo" no menu superior, incluindo "Salvar como" e "Compartilhar". Além disso, é possível exportar a apresentação em vários formatos, incluindo PDF, vídeo e HTML.<br/><br/>Essas são algumas dicas básicas para começar a usar o PowerPoint. Lembre-se de explorar as opções e recursos disponíveis para personalizar e aprimorar sua apresentação. Algumas outras dicas incluem:<br/><br/>Utilizar as opções de layout para organizar o conteúdo de forma clara e atraente<br/><br/>Utilizar efeitos de animação para chamar a atenção dos espectadores para elementos importantes<br/><br/>Utilizar transições suaves entre slides para manter a fluidez da apresentação<br/><br/>Utilizar imagens e gráficos para ilustrar dados.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 7 
    },
    ppoint1Aula2 : { 
        nome: '2', 
        titulo: 'Formatação de Slides', 
        conteudo: `A formatação de slides é uma parte importante do processo de criação de uma apresentação no PowerPoint. É possível adicionar diferentes tipos de conteúdo, como texto, imagens, gráficos e outros elementos visuais, para tornar sua apresentação mais atraente e eficaz. Aqui estão algumas dicas para ajudá-lo a formatar seus slides:<br/><br/>Adicionando texto: Para adicionar texto a um slide, você pode clicar na ferramenta "Texto" na guia "Início" ou selecionar "Adicionar texto" no menu do botão direito do mouse. Em seguida, você pode digitar ou colar o texto desejado. É possível formatar o texto, como alterar a fonte, o tamanho e a cor, usando as opções no painel de tarefas.<br/><br/>Adicionando imagens: Para adicionar imagens a um slide, você pode clicar na ferramenta "Imagem" na guia "Início" ou selecionar "Adicionar imagem" no menu do botão direito do mouse. Em seguida, você pode selecionar a imagem desejada a partir do seu computador ou de uma fonte on-line. É possível redimensionar e ajustar a imagem usando as opções no painel de tarefas.<br/><br/>Adicionando gráficos: Para adicionar gráficos a um slide, você pode clicar na ferramenta "Gráfico" na guia "Início" ou selecionar "Adicionar gráfico" no menu do botão direito do mouse. Em seguida, você pode escolher o tipo de gráfico desejado, como um gráfico de barras, de linhas ou de pizza, e inserir os dados. É possível personalizar o gráfico, como alterar cores e estilos, usando as opções no painel de tarefas.<br/><br/>Adicionando outros elementos visuais: Além de texto, imagens e gráficos, você também pode adicionar outros elementos visuais aos slides, como formas, ícones, tabelas e vídeos. Para adicionar esses elementos, você pode usar as ferramentas na guia "Início" ou selecionar "Adicionar elemento" no menu do botão direito do mouse.<br/><br/>Lembre-se de que a formatação de slides é uma parte importante do processo de criação de uma apresentação eficaz. Certifique-se de usar as opções e recursos disponíveis para organizar o conteúdode forma clara e atraente, evitando excesso de informações e distrações desnecessárias. Além disso, é importante usar imagens e gráficos de alta qualidade e garantir que eles estejam alinhados com o tema e o objetivo da sua apresentação. Por fim, lembre-se de testar sua apresentação antes de apresentá-la, para garantir que tudo esteja funcionando corretamente.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 7 
    },
    ppoint1Aula3 : { 
        nome: '3', 
        titulo: 'Atividade', 
        conteudo: `Atividade:<br/><br/>Abra o PowerPoint e crie uma nova apresentação. Escolha um modelo pré-projetado ou crie uma apresentação em branco.<br/><br/>Adicione pelo menos 5 slides à sua apresentação, usando diferentes tipos de slides, como títulos, conteúdo, comparação, tópicos, etc.<br/><br/>Adicione conteúdo, como texto, imagens, gráficos e vídeos, à sua apresentação. Utilize as ferramentas na guia "Início" e no painel de tarefas para formatar o texto, adicionar efeitos e transições e personalizar a aparência da apresentação.<br/><br/>Utilize as opções de layout para organizar o conteúdo de forma clara e atraente. Adicione efeitos de animação para chamar a atenção dos espectadores para elementos importantes. Utilize transições suaves entre slides para manter a fluidez da apresentação.<br/><br/>Utilize imagens e gráficos para ilustrar dados e tornar a apresentação mais interessante. Utilize o recurso de narrativa para adicionar áudio à apresentação e torná-la mais interativa.<br/><br/>Salve e compartilhe sua apresentação com outros usando as opções de "Arquivo" no menu superior, incluindo "Salvar como" e "Compartilhar". Experimente exportar a apresentação em diferentes formatos, como PDF, vídeo e HTML.<br/><br/>Após concluir a atividade, reflita sobre como as dicas e recursos do PowerPoint ajudaram a criar uma apresentação atraente e eficaz. Pense em como você pode usar esses recursos em futuras apresentações.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 7 
    },
    ppoint1Aula4 : { 
        nome: '4', 
        titulo: 'Design e layout', 
        conteudo: `Design e layout são elementos importantes na criação de uma apresentação atraente e profissional no PowerPoint. Aqui estão algumas dicas para ajudá-lo a controlar o design e o layout de sua apresentação:<br/><br/>Escolha e personalize um modelo de slide: O PowerPoint vem com uma variedade de modelos de slide pré-projetados que você pode usar como base para sua apresentação. Você pode escolher um modelo de slide na guia "Início" ou selecionar "Novo slide" no menu do botão direito do mouse. Em seguida, você pode personalizar o modelo, como alterar as cores e fontes, usando as opções no painel de tarefas.<br/><br/>Controlar a disposição dos elementos: Para controlar a disposição dos elementos em um slide, você pode usar as ferramentas de alinhamento e distribuição na guia "Formatar". Isso permite que você alinhe elementos uns aos outros e ajuste o espaçamento entre eles. Também é possível usar o recurso de grade e guias para ajudar a posicionar os elementos.<br/><br/>Criar sua própria paleta de cores: Para criar sua própria paleta de cores, você pode usar a ferramenta "Cores" na guia "Exibição". Isso permite que você escolha as cores para seus elementos de forma precisa e consistente, e salvar sua paleta de cores para uso futuro.<br/><br/>Lembre-se que o design e o layout são elementos importantes na criação de uma apresentação eficaz. Certifique-se de usar as opções e recursos disponíveis para criar uma apresentação que seja atraente, fácil de seguir e profissional.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 7 
    },
    ppoint1Aula5 : { 
        nome: '5', 
        titulo: 'Atividade', 
        conteudo: `Atividade: Design e Layout Profissional no PowerPoint<br/><br/>Escolha e personalize um modelo de slide:<br/><br/>Abra o PowerPoint e selecione a guia "Início".<br/><br/>Escolha um modelo de slide que seja apropriado para o tema da sua apresentação e clique em "Criar".<br/><br/>Personalize o modelo escolhido alterando as cores e fontes, usando as opções no painel de tarefas.<br/><br/>Controlar a disposição dos elementos:<br/><br/>Adicione elementos à sua apresentação, como imagens, gráficos e textos.<br/><br/>Selecione os elementos e vá para a guia "Formatar".<br/><br/>Utilize as ferramentas de alinhamento e distribuição para alinhar elementos uns aos outros e ajustar o espaçamento entre eles.<br/><br/>Use o recurso de grade e guias para ajudar a posicionar os elementos.<br/><br/>Criar sua própria paleta de cores:<br/><br/>Vá para a guia "Exibição" e selecione "Cores".<br/><br/>Escolha suas cores desejadas para os elementos da sua apresentação de forma precisa e consistente.<br/><br/>Salve sua paleta de cores para uso futuro.<br/><br/>Revisão final:<br/><br/>Verifique se sua apresentação tem uma disposição clara e consistente.<br/><br/>Certifique-se de que as cores escolhidas sejam coerentes e atraentes.<br/><br/>Verifique se todos os elementos estão alinhados e espaçados corretamente.<br/><br/>Verifique se sua apresentação é fácil de seguir e profissional.<br/><br/>Lembre-se de que o design e o layout são elementos importantes na criação de uma apresentação eficaz. Certifique-se de usar as opções e recursos disponíveis para criar uma apresentação que seja atraente, fácil de seguir e profissional.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 7 
    },
    ppoint1Aula6 : { 
        nome: '6', 
        titulo: 'Compartilhar e colaborar Apresentações', 
        conteudo: `Compartilhar e colaborar em apresentações no PowerPoint pode ser feito de várias maneiras, incluindo:<br/><br/>Salvar e compartilhar: Você pode salvar sua apresentação no seu computador ou em um serviço de armazenamento na nuvem, como o OneDrive ou o Google Drive. Isso permite que você acesse e compartilhe sua apresentação em qualquer lugar. Além disso, você pode enviar o arquivo de apresentação por e-mail ou compartilhá-lo com um link.<br/><br/>Trabalhar em equipe: O PowerPoint também permite que você trabalhe em equipe em uma apresentação. Você pode compartilhar a apresentação com outras pessoas e permitir que elas editem ao mesmo tempo. Isso é útil quando você precisa de feedback ou contribuições de outras pessoas.<br/><br/>Comentários e revisão: O PowerPoint tem recursos de comentários e revisão que permitem que você e outras pessoas adicionem comentários e sugestões à sua apresentação. Isso é útil para obter feedback e fazer ajustes antes de compartilhar a apresentação com um público maior.<br/><br/>Para compartilhar e colaborar em uma apresentação no PowerPoint, você precisará primeiro salvar o arquivo e, em seguida, compartilhar o arquivo usando as opções disponíveis. Certifique-se de definir as permissões de acesso corretamente para garantir que somente as pessoas autorizadas possam editar ou visualizar sua apresentação. Além disso, use os recursos de comentários e revisão para obter feedback e fazer ajustes antes de compartilhar a apresentação com um público maior.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 7 
    },
    

    ppoint2Aula1 : { 
        nome: '1', 
        titulo: 'Tabelas e Gráficos', 
        conteudo: `Criação de tabelas e gráficos é uma das formas mais eficazes de apresentar dados e informações em suas apresentações de PowerPoint. Aqui estão algumas dicas para ajudá-lo a criar tabelas e gráficos atraentes e informativos:<br/><br/>Escolha o tipo de tabela ou gráfico certo: Escolha o tipo de tabela ou gráfico que melhor se adapte aos dados que você deseja apresentar. Existem vários tipos de tabelas e gráficos disponíveis no PowerPoint, como tabelas, gráficos de barras, gráficos de linhas, gráficos de pizza, entre outros.<br/><br/>Insira e formate dados: Insira os dados em sua tabela ou gráfico usando a guia "Inserir" no menu do PowerPoint. Em seguida, use as opções de formatação para personalizar a aparência de sua tabela ou gráfico, como alterar as cores, fontes e tamanhos.<br/><br/>Adicionar legendas e rótulos: Adicionar legendas e rótulos ajuda a tornar seus dados mais fáceis de ler e entender. Utilize a guia "Exibir" para adicionar legendas e rótulos a seus gráficos e tabelas.<br/><br/>Adicionar efeitos visuais: Adicionar efeitos visuais, como sombras e contornos, ajuda a destacar seus dados e tornar sua tabela ou gráfico mais atraente. Utilize a guia "Formatar" para adicionar efeitos visuais a seus gráficos e tabelas.<br/><br/>Utilizar recursos de análise: O PowerPoint oferece recursos de análise de dados, como ferramentas de tendência, que podem ajudá-lo a identificar padrões e tendências em seus dados. Utilize esses recursos para obter insights adicionais e melhorar a eficácia de sua apresentação.<br/><br/>Lembre-se que tabelas e gráficos são uma excelente maneira de apresentar dados e informações de maneira clara e concisa. Certifique-se de usar as opções e recursos disponíveis para criar tabelas e gráficos atraentes e informativos que ajudem a comunicar sua mensagem.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },
    ppoint2Aula2 : { 
        nome: '2', 
        titulo: 'Atividade', 
        conteudo: `Atividade:<br/><br/>Escolha um conjunto de dados que você deseja apresentar em sua próxima apresentação de PowerPoint. Pode ser sobre vendas, estatísticas, dados demográficos, etc.<br/><br/>Crie uma tabela ou gráfico para mostrar esses dados, seguindo as dicas acima. Certifique-se de escolher o tipo de tabela ou gráfico certo, inserir e formatar seus dados, adicionar legendas e rótulos, adicionar efeitos visuais e utilizar recursos de análise.<br/><br/>Salve sua tabela ou gráfico e adicione-o à sua apresentação de PowerPoint. Certifique-se de que sua tabela ou gráfico esteja legível e fácil de entender.<br/><br/>Apresente sua tabela ou gráfico para um colega ou amigo e peça sua opinião sobre como ele(a) achou que a tabela ou gráfico se saiu. Peça sugestões sobre como você pode melhorá-lo.<br/><br/>Faça as alterações sugeridas e revise sua tabela ou gráfico novamente. Certifique-se de que ele seja atraente, informativo e fácil de entender antes de incluí-lo em sua apresentação final.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },
    ppoint2Aula3 : { 
        nome: '3', 
        titulo: 'Vídeo e Som', 
        conteudo: `Adição de vídeo e som às suas apresentações de PowerPoint pode ajudar a torná-las mais envolventes e interessantes para o público. Aqui estão algumas dicas para ajudá-lo a adicionar vídeo e som às suas apresentações:<br/><br/>Adicionar vídeo: Para adicionar um vídeo à sua apresentação, você pode usar a guia "Inserir" no menu do PowerPoint e selecionar "Vídeo" para adicionar um vídeo armazenado em seu computador ou usar a opção "Vídeo da Internet" para adicionar um vídeo do YouTube ou outro site de compartilhamento de vídeos.<br/><br/>Formatar vídeo: Depois de adicionar um vídeo à sua apresentação, você pode usar as opções de formatação para personalizar a aparência do vídeo, como alterar o tamanho e a posição do vídeo na tela.<br/><br/>Adicionar som: Para adicionar som à sua apresentação, você pode usar a guia "Inserir" no menu do PowerPoint e selecionar "Som" para adicionar um arquivo de som armazenado em seu computador. Você também pode usar a opção "Som da Internet" para adicionar uma música ou outro som de um site de compartilhamento de música.<br/><br/>Controlar som: Depois de adicionar som à sua apresentação, você pode usar as opções de controle de som para gerenciar a reprodução do som, como reproduzir, pausar e parar a reprodução do som.<br/><br/>Lembre-se que vídeo e som podem ajudar a tornar suas apresentações mais envolventes e interessantes para o público. Certifique-se de usar as opções e recursos disponíveis para adicionar vídeo e som às suas apresentações de maneira eficaz.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },
    ppoint2Aula4 : { 
        nome: '4', 
        titulo: 'Atividade', 
        conteudo: `Atividade:<br/><br/>Crie uma nova apresentação no PowerPoint.<br/><br/>Escolha uma cena ou cenas de um vídeo de sua escolha e adicione-o à sua apresentação usando a guia "Inserir" e selecionando "Vídeo" ou "Vídeo da Internet".<br/><br/>Experimente usar as opções de formatação para personalizar a aparência do vídeo, como alterar o tamanho e a posição do vídeo na tela.<br/><br/>Escolha uma música ou outro som de sua escolha e adicione-o à sua apresentação usando a guia "Inserir" e selecionando "Som" ou "Som da Internet".<br/><br/>Experimente usar as opções de controle de som para gerenciar a reprodução do som, como reproduzir, pausar e parar a reprodução do som.<br/><br/>Salve sua apresentação e teste-a para ver como o vídeo e o som afetam a sua apresentação.<br/><br/>Refleça sobre como você pode usar vídeo e som de maneira eficaz em suas futuras apresentações para torná-las mais envolventes e interessantes para o público.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },
    ppoint2Aula5 : { 
        nome: '5', 
        titulo: 'Apresentações para Web', 
        conteudo: `Criar apresentações para web é uma ótima maneira de compartilhar informações e conteúdo com um público amplo e em diferentes dispositivos. Aqui estão algumas dicas para ajudá-lo a criar apresentações para web:<br/><br/>Escolha uma ferramenta de criação de apresentações: Existem várias ferramentas disponíveis para criar apresentações para web, como o PowerPoint, o Google Slides, o Prezi, entre outros. Escolha a ferramenta que melhor atende às suas necessidades e às suas habilidades.<br/><br/>Utilize recursos multimídia: As apresentações para web são mais atraentes quando incluem recursos multimídia, como imagens, vídeos e áudios. Isso ajuda a tornar as informações mais interessantes e fáceis de serem entendidas.<br/><br/>Faça uso de animações e transições: As animações e transições ajudam a criar uma sensação de movimento e dinamismo na sua apresentação. Isso ajuda a manter a atenção do público.<br/><br/>Otimize para dispositivos móveis: As apresentações para web devem ser otimizadas para serem visualizadas em diferentes dispositivos, como computadores, tablets e smartphones. Isso garante que todos os seus espectadores possam acessar e visualizar sua apresentação com facilidade.<br/><br/>Compartilhe sua apresentação: Depois de criar sua apresentação, você pode compartilhá-la através de várias plataformas, como o YouTube, o Vimeo, o Slideshare, entre outros. Isso permitirá que mais pessoas vejam sua apresentação e a compartilhem com outras pessoas.<br/><br/>Utilize as ferramentas de edição e personalização de sua ferramenta escolhida para adaptar sua apresentação para diferentes tamanhos de tela e formatos.<br/><br/>Lembre-se de que a criação de apresentações para web é uma forma eficaz de compartilhar informações e conteúdo com um público amplo e em diferentes dispositivos. Com essas dicas, você poderá criar apresentações atraentes e eficazes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },
    ppoint2Aula6 : { 
        nome: '6', 
        titulo: 'Atividade', 
        conteudo: `Atividade:<br/><br/>Escolha uma ferramenta de criação de apresentações, como o PowerPoint, o Google Slides ou o Prezi.<br/><br/>Crie uma apresentação sobre um tópico de sua escolha.<br/><br/>Adicione recursos multimídia, como imagens, vídeos e áudios para tornar a apresentação mais interessante e fácil de entender.<br/><br/>Utilize animações e transições para criar uma sensação de movimento e dinamismo.<br/><br/>Otimize a apresentação para ser visualizada em diferentes dispositivos, como computadores, tablets e smartphones.<br/><br/>Compartilhe a apresentação em uma plataforma de sua escolha, como o YouTube, o Vimeo ou o Slideshare.<br/><br/>Utilize as ferramentas de edição e personalização de sua ferramenta escolhida para adaptar sua apresentação para diferentes tamanhos de tela e formatos.<br/><br/>Analise o resultado final e faça sugestões para melhorias futuras.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },
    ppoint2Aula7 : { 
        nome: '7', 
        titulo: 'Apresentações Interativas', 
        conteudo: `Criação de apresentações interativas é uma ótima maneira de tornar sua apresentação mais engajadora e envolvente para o público. Aqui estão algumas dicas para ajudá-lo a criar apresentações interativas:<br/><br/>Utilize hyperlinks: Hyperlinks são links que permitem que os espectadores naveguem para outras páginas ou recursos da web a partir da sua apresentação. Isso pode incluir links para outras apresentações, sites ou vídeos relacionados.<br/><br/>Adicione botões de ação: Botões de ação são elementos interativos que permitem que os espectadores realizem ações, como avançar para a próxima slide ou retornar para a slide anterior. Isso ajuda a tornar a apresentação mais fácil de seguir e navegar.<br/><br/>Utilize questionários e enquete: Questionários e enquete permitem que os espectadores respondam perguntas e dê sua opinião sobre o conteúdo da apresentação. Isso ajuda a tornar a apresentação mais interativa e engajadora.<br/><br/>Utilize recursos de mídia interativa: Como vídeos, áudios e fotos interativos permitem que os espectadores explorem conteúdo adicional e tornam a apresentação mais envolvente.<br/><br/>Utilize aplicativos interativos: Existem vários aplicativos e ferramentas disponíveis que permitem criar apresentações interativas, como o Prezi, o H5P, o Adobe Captivate, entre outros.<br/><br/>Otimize para dispositivos móveis: As apresentações interativas devem ser otimizadas para serem visualizadas em diferentes dispositivos, como computadores, tablets e smartphones. Isso garante que todos os seus espectadores possam acessar e interagir com sua apresentação com facilidade.<br/><br/>Lembre-se de que a criação de apresentações interativas é uma forma eficaz de tornar sua apresentação mais engajadora e envolvente para o público. Com essas dicas, você poderá criar apresentações interativas atraentes e eficazes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },
    ppoint2Aula8 : { 
        nome: '8', 
        titulo: 'Atividade', 
        conteudo: `Atividade:<br/><br/>Escolha um tema para sua apresentação e crie um roteiro.<br/><br/>Utilize o software de sua escolha para criar sua apresentação.<br/><br/>Adicione hyperlinks relacionados ao tema da sua apresentação para que os espectadores possam explorar conteúdo adicional.<br/><br/>Adicione botões de ação para que os espectadores possam avançar ou voltar entre as slides.<br/><br/>Inclua questionários ou enquete para que os espectadores possam dar sua opinião sobre o conteúdo da apresentação.<br/><br/>Adicione recursos de mídia interativa, como vídeos, áudios e fotos interativos para tornar a apresentação mais envolvente.<br/><br/>Teste sua apresentação em diferentes dispositivos para garantir que ela esteja otimizada para visualização em dispositivos móveis.<br/><br/>Apresente sua apresentação interativa para um grupo pequeno e peça feedback para saber o que pode ser melhorado.<br/><br/>Faça as alterações necessárias e apresente para um grupo maior.<br/><br/>Obs: Alguns softwares para criação de apresentações interativas incluem o PowerPoint, Prezi, Adobe Captivate, H5P, entre outros. Cada um deles possui suas particularidades e recursos específicos, então é importante escolher aquele que melhor se adequa às necessidades e habilidades do usuário.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 8 
    },


    ppoint3Aula1 : { 
        nome: '1', 
        titulo: 'Layouts e Modelos ', 
        conteudo: `A personalização avançada de layouts e modelos de slide é uma técnica para criar apresentações mais atraentes e profissionais. Aqui estão algumas dicas para ajudá-lo a personalizar layouts e modelos de slide:<br/><br/>Escolha um layout de slide que seja apropriado para o conteúdo da sua apresentação. Existem vários layouts diferentes disponíveis, incluindo layouts de título, conteúdo, citação, comparação e muito mais. Escolha o layout que melhor se adapte às necessidades da sua apresentação.<br/><br/>Utilize modelos de slide para economizar tempo e manter a consistência da sua apresentação. Modelos de slide incluem elementos de design, como fontes, cores e imagens, que podem ser personalizados para atender às necessidades da sua apresentação.<br/><br/>Utilize recursos de formatação avançada para personalizar a aparência dos elementos da sua apresentação. Isso inclui opções de formatação de texto, como fonte, tamanho, cor e alinhamento, bem como opções de formatação de imagens, como tamanho, posição e efeitos de imagem.<br/><br/>Utilize recursos de animação para criar transições suaves entre slides e para chamar a atenção do público para elementos específicos da sua apresentação. Existem vários efeitos de animação disponíveis, incluindo desvanecer, aparecer e mover.<br/><br/>Utilize gráficos e tabelas para ilustrar dados e informações. Isso ajuda a tornar a apresentação mais fácil de entender e mais atraente para o público.<br/><br/>Otimize a sua apresentação para a projeção. Certifique-se de que as fontes são legíveis, as cores são vibrantes e as imagens são nítidas quando projetadas.<br/><br/>Lembre-se de que a personalização avançada de layouts e modelos de slide é uma técnica importante para criar apresentações profissionais e atraentes. Utilizando essas dicas, você poderá criar apresentações que sejam eficazes e impressionem o seu público.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 9 
    },
    ppoint3Aula2 : { 
        nome: '2', 
        titulo: 'Conteúdo Interativo', 
        conteudo: `A criação de apresentações com conteúdo interativo, como questionários e jogos, é uma ótima maneira de tornar sua apresentação mais engajadora e envolvente para o público. Algumas dicas para criar apresentações interativas incluem:<br/><br/>Utilize questionários e enquete: Questionários e enquete permitem que os espectadores respondam perguntas e dêem sua opinião sobre o conteúdo da apresentação. Isso ajuda a tornar a apresentação mais interativa e engajadora.<br/><br/>Utilize jogos: Jogos, como caça-palavras, cruzadinhas, etc, são uma ótima maneira de envolver o público e ajudar a fixar o conteúdo.<br/><br/>Incorpore vídeos e áudios interativos: Vídeos e áudios interativos permitem que os espectadores explorem conteúdo adicional e tornam a apresentação mais envolvente.<br/><br/>Utilize aplicativos interativos: Existem vários aplicativos e ferramentas disponíveis que permitem criar apresentações interativas, como o Prezi, o H5P, o Adobe Captivate, entre outros.<br/><br/>Otimize para dispositivos móveis: As apresentações interativas devem ser otimizadas para serem visualizadas em diferentes dispositivos, como computadores, tablets e smartphones. Isso garante que todos os seus espectadores possam acessar e interagir com sua apresentação com facilidade.<br/><br/>Lembre-se de que a criação de apresentações interativas é uma forma eficaz de tornar sua apresentação mais engajadora e envolvente para o público. Com essas dicas, você poderá criar apresentações interativas atraentes e eficazes.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 9 
    },
    ppoint3Aula3 : { 
        nome: '3', 
        titulo: 'Atividade', 
        conteudo: `Atividade:<br/><br/>Crie uma apresentação sobre um assunto de sua escolha e adicione um questionário no início da apresentação para que os espectadores possam responder perguntas relacionadas ao assunto.<br/><br/>Incorpore um jogo interativo, como uma caça-palavras ou cruzadinha, relacionado ao assunto da apresentação.<br/><br/>Adicione um vídeo ou áudio interativo que os espectadores possam assistir e explorar conteúdo adicional.<br/><br/>Utilize um aplicativo ou ferramenta para criar sua apresentação interativa, como o Prezi, o H5P ou o Adobe Captivate.<br/><br/>Otimize sua apresentação para ser visualizada em dispositivos móveis, como smartphones e tablets.<br/><br/>Apresente sua apresentação interativa para um grupo de pessoas e solicite feedback sobre como eles acharam a interatividade e se ela ajudou a tornar a apresentação mais engajadora e envolvente.<br/><br/>Faça alterações de acordo com o feedback recebido e refaça a apresentação até que esteja satisfeito com o resultado final.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 9 
    },
    ppoint3Aula4 : { 
        nome: '4', 
        titulo: 'Apresentações Automatizadas', 
        conteudo: `A criação de apresentações automatizadas é uma técnica avançada que permite que você crie apresentações com recursos como apresentações de voz e vídeo. Isso é útil quando você precisa criar apresentações de forma rápida e eficiente, sem precisar ficar parado diante do público.<br/><br/>Existem várias ferramentas e aplicativos que permitem criar apresentações automatizadas, incluindo o PowerPoint, o Adobe Captivate, o Articulate Storyline e o Adobe Premiere. Essas ferramentas geralmente oferecem recursos como a adição de áudio e vídeo, animações, efeitos de transição, etc.<br/><br/>Para criar uma apresentação automatizada, você precisará primeiro escolher uma ferramenta ou aplicativo para criar sua apresentação. Em seguida, você deve adicionar seu conteúdo, incluindo texto, imagens, áudio e vídeo. Em seguida, você pode adicionar animações e efeitos para tornar a apresentação mais atraente.<br/><br/>Em seguida, você pode adicionar recursos de apresentação de voz, como narração automatizada, para que a apresentação possa ser reproduzida sem a sua presença. Por fim, você pode exportar a apresentação em um formato compatível com a sua necessidade, como apresentação HTML5, MP4, etc.<br/><br/>Tenha em mente que é importante testar a apresentação antes de apresentá-la ao público para garantir que tudo está funcionando corretamente. Além disso, certifique-se de que sua apresentação esteja otimizada para dispositivos móveis, para garantir que todos os seus espectadores possam visualizá-la com facilidade.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 9 
    },
    ppoint3Aula5 : { 
        nome: '5', 
        titulo: 'Atividade', 
        conteudo: `Atividade avançada de PowerPoint:<br/><br/>Abra o PowerPoint e crie uma nova apresentação vazia.<br/><br/>Adicione uma nova slide e selecione o layout "Comparação" para mostrar a comparação entre dois ou mais itens.<br/><br/>Utilize as ferramentas de design avançadas para personalizar o slide. Adicione formas, texto e desenhos para destacar as diferenças entre os itens comparados. Utilize recursos como gradientes, sombra e contorno para dar profundidade e destaque aos elementos.<br/><br/>Utilize a função de animação para criar efeitos interessantes. Por exemplo, você pode fazer com que os elementos apareçam em sequência, ou que os elementos aumentem ou diminuam de tamanho para destacar as diferenças.<br/><br/>Adicione recursos interativos, como questionários e jogos, para envolver a audiência e tornar a apresentação mais interessante. Utilize aplicativos interativos como o Prezi, H5P, Adobe Captivate entre outros.<br/><br/>Adicione apresentação de voz e vídeo para tornar a apresentação mais envolvente. Utilize a opção de gravação de voz e vídeo para adicionar comentários e explicações adicionais.<br/><br/>Salve a sua apresentação e teste-a em diferentes dispositivos, incluindo computadores, tablets e smartphones, para garantir que ela esteja otimizada para todos os dispositivos.<br/><br/>Compartilhe a apresentação com sua audiência e obtenha feedback para continuar aprimorando e melhorando sua apresentação.<br/><br/>Essa atividade é um exemplo de como você pode utilizar recursos avançados do PowerPoint para criar uma apresentação interativa e envolvente. Lembre-se de que essa é apenas uma das muitas possibilidades que o PowerPoint oferece e que você deve experimentar e brincar com as ferramentas para encontrar as melhores maneiras de usá-las para atender suas necessidades.`, 
        video: 'https://www.youtube.com/embed/ilwewVTh1R4', 
        cursoId: 9 
    },

}